In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
import joblib
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [3]:
df = pd.read_csv("F:\\Dataset\\07. Advertising.csv")

In [4]:
df.head()

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [6]:
df = df.iloc[:, 1:]

In [7]:
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [8]:
df.tail()

        TV  Radio  Newspaper  Sales
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

In [9]:
df.isnull().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [10]:
df.duplicated().sum()

0

In [11]:
df.dtypes

TV           float64
Radio        float64
Newspaper    float64
Sales        float64
dtype: object

In [12]:
df.shape

(200, 4)

In [13]:
X = df.drop("Sales", axis = 1)

In [14]:
X

        TV  Radio  Newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [15]:
y = df.Sales

In [16]:
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ...
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales, Length: 200, dtype: float64

In [17]:
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=45)

In [18]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((160, 3), (40, 3), (160,), (40,))

In [19]:
scl = StandardScaler()

In [20]:
x_train_scl = scl.fit_transform(x_train)

In [21]:
x_test_scl = scl.transform(x_test)

In [22]:
lr = LinearRegression()

In [23]:
lr.fit(x_train_scl, y_train)

LinearRegression()

In [24]:
lr.coef_

array([ 4.07686894,  2.76432822, -0.10958854])

In [25]:
lr.intercept_

13.87125

In [26]:
lr.score(x_test_scl, y_test)

0.8955882331233613

In [27]:
y_pred = lr.predict(x_test_scl)

In [28]:
pd.DataFrame({"y_true": y_test, "y_pred":y_pred})

     y_true     y_pred
45     14.9  15.188873
72      8.8  10.205411
40     16.6  16.439320
58     23.8  21.808189
25     12.0  15.887521
13      9.7   8.926802
153    19.0  18.135673
80     11.8  11.365894
3      18.5  17.397555
44      8.5   8.669504
134    10.8  11.482201
149    10.1   9.719351
173    11.7  12.139678
33     17.4  19.134917
62     15.7  16.942065
182     8.7   6.527936
112    14.1  14.056052
129     9.7   7.778336
69     22.3  21.095499
190    10.8  12.353939
133    19.6  19.241405
172     7.6   7.511594
35     12.8  17.357531
157    10.1  10.145578
187    17.3  17.142930
10      8.6   7.038274
104    20.7  20.446466
177    11.7  12.243723
26     15.0  15.015156
171    14.5  14.319856
147    25.4  23.188599
0      22.1  20.397088
109    19.8  19.896170
194    17.3  16.522626
151    11.6   9.976042
82     11.3  10.090430
64     18.0  16.858068
169    15.0  18.259486
4      12.9  13.179382
28     18.9  19.538061

In [29]:
mean_absolute_error(y_test, y_pred)

1.0788802763848646

In [31]:
mse = mean_squared_error(y_test, y_pred)

In [32]:
np.sqrt(mse)

1.5021631892976657

In [33]:
r2_score(y_test, y_pred)

0.8955882331233613

## ridge

In [34]:
ridge = Ridge()

In [ ]:
ridge.fit(x_train_scl, y_train)

Ridge()

In [36]:
ridge.coef_

array([ 4.05174647,  2.74479232, -0.09907862])

In [37]:
ridge.score(x_test_scl, y_test)

0.8962555330609423

### lasso

In [38]:
l1 = Lasso()

In [39]:
l1.fit(x_train_scl, y_train)

Lasso()

In [40]:
l1.coef_

array([3.12845271, 1.78319971, 0.        ])

In [41]:
l1.score(x_test_scl, y_test)

0.8236670415610957

### Elasticnet

In [42]:
el= ElasticNet()

In [43]:
el.fit(x_train_scl, y_train)

ElasticNet()

In [44]:
el.coef_

array([2.42826611, 1.54949022, 0.00935345])

In [45]:
el.score(x_test_scl, y_test)

0.7490238769673028