## Mysql

In [ ]:
!pip install pymysql

In [ ]:
#!pip uninstall sqlalchemy

In [1]:
import pymysql

In [3]:
# make a connection with mysql
mydb = pymysql.connect(
  host="localhost",
  user="root",
  password="12345"
)

In [5]:
#create a database in mysql 
cursor = mydb.cursor()

In [7]:
cursor.execute("show databases")
for x in cursor:
  print(x)

('bulk_load',)
('class11',)
('class8',)
('class9',)
('da_carburator_project',)
('information_schema',)
('laptop_data',)
('mysql',)
('performance_schema',)
('pydatabase',)
('sakila',)
('sys',)
('world',)

In [8]:
cursor.execute("create database newdb")

1

In [9]:
cursor.execute("show databases")
for x in cursor:
  print(x)

('bulk_load',)
('class11',)
('class8',)
('class9',)
('da_carburator_project',)
('information_schema',)
('laptop_data',)
('mysql',)
('newdb',)
('performance_schema',)
('pydatabase',)
('sakila',)
('sys',)
('world',)

In [10]:
cursor.execute("use newdb")

0

In [14]:
cursor.execute("show tables")
for x in cursor:
  print(x)

('customer',)

In [13]:
cursor.execute("CREATE TABLE customer (name VARCHAR(255), address VARCHAR(255))")

0

In [16]:
cursor.execute("alter table customer add column id int first")

0

In [18]:
sql = "INSERT INTO customer (id, name, address) VALUES (%s, %s, %s)"

val = ("1","ROHIT", "Highway 21")

cursor.execute(sql, val)

mydb.commit()

In [19]:
cursor.execute("select * from customer")

for i in cursor:
    print(i)

(1, 'ROHIT', 'Highway 21')
(1, 'ROHIT', 'Highway 21')

In [21]:
sql = "INSERT INTO customer(id, name, address) VALUES (%s, %s, %s)"
val = [("2","ROHIT", "Highway 21"),
  ("3", 'Peter', 'Lowstreet 4'),
  ("4",'Ammy', 'Apple st 652'),
  ("5",'Huma', 'Mountain 21')]

In [23]:
cursor.executemany(sql, val)

4

In [24]:
mydb.commit()

In [31]:
cursor.execute("select * from customer")

for i in cursor:
    print(i)

(1, 'john', 'Highway 21')
(1, 'john', 'Highway 21')
(3, 'Peter', 'Lowstreet 4')
(4, 'Ammy', 'Apple st 652')
(5, 'Huma', 'Mountain 21')

In [27]:
sql = "UPDATE customer SET name = 'john' WHERE id = '1'"

cursor.execute(sql)

mydb.commit()

print(cursor.rowcount, "record(s) affected")

2 record(s) affected

In [ ]:
sql = "DELETE FROM customer WHERE id = '2'"

cursor.execute(sql)

mydb.commit()

print(cursor.rowcount, "record(s) deleted")

0 record(s) deleted

In [33]:
cursor.execute("select * from customer where id in (3,4,5)")
for i in cursor:
    print(i)

(3, 'Peter', 'Lowstreet 4')
(4, 'Ammy', 'Apple st 652')
(5, 'Huma', 'Mountain 21')

In [34]:
cursor.execute("use laptop_data")

0

In [35]:
cursor.execute("select * from laptop_price")

for i in cursor:
    print(i)

('LTP00001', 'Avita', 'Notebook', 'i5-11400H', '8GB', '256GB SSD', 'None', 'Integrated', 14.0, 'FHD', 1.5, 'Windows 11', 'Notebook', 5.5, 'No', 42000, None)
('LTP00002', 'Microsoft', 'Notebook', 'Ryzen 7 5700U', '16GB', '256GB SSD', 'None', 'MX550 2GB', 14.0, 'FHD', 1.8, 'Windows 11', 'Notebook', 5.8, 'No', 93000, None)
('LTP00003', 'HP', 'Netbook', 'i3-1215U', '8GB', '512GB HDD', 'None', 'MX550 2GB', 11.6, 'FHD', 1.1, 'macOS', 'Netbook', 8.2, 'No', 33000, None)
('LTP00004', 'Apple', 'Ultrabook', 'Apple M1', '4GB', '256GB SSD', 'None', 'Integrated', 13.3, 'Retina', 1.9, 'macOS', 'Ultrabook', 17.2, 'No', 88000, None)
('LTP00005', 'Apple', 'Notebook', 'Apple M1 Pro', '8GB', '512GB SSD', 'None', 'Integrated', 14.0, 'Retina', 2.0, 'macOS', 'Notebook', 13.0, 'No', 112000, None)
('LTP00006', 'MSI', 'Notebook', 'i9-12900H', '8GB', '256GB SSD', 'None', 'Integrated', 15.6, 'FHD', 1.7, 'macOS', 'Notebook', 9.7, 'No', 95000, None)
('LTP00007', 'Avita', 'Ultrabook', 'Ryzen 7 5800H', '8GB', '1TB SSD', 'None', 'MX550 2GB', 14.0, 'FHD', 1.4, 'Windows 11', 'Ultrabook', 7.9, 'No', 60000, None)
('LTP00008', 'Lenovo', 'Ultrabook', 'i5-1135G7', '8GB', '256GB SSD', 'None', 'Integrated', 14.0, 'FHD', 1.4, 'Windows 10', 'Ultrabook', 8.0, 'No', 48000, None)
('LTP00009', 'Microsoft', 'Gaming Series', 'i5-12500H', '32GB', '1TB SSD', '1TB HDD', 'RTX 4060 8GB', 16.0, 'FHD', 2.3, 'Windows 10', 'Gaming Series', 4.4, 'No', 185000, None)
('LTP00010', 'Acer', 'Business Series', 'i7-1255U', '8GB', '2TB SSD', 'None', 'GTX 1650 4GB', 14.0, 'HD', 2.1, 'Windows 10', 'Business Series', 7.7, 'No', 99000, None)
('LTP00011', 'Dell', 'Ultrabook', 'Ryzen 9 5900HS', '16GB', '512GB SSD', 'None', 'Integrated', 13.3, 'FHD', 1.9, 'Windows 10', 'Ultrabook', 5.4, 'No', 72000, None)
('LTP00012', 'Microsoft', 'Gaming Series', 'i7-12700H', '16GB', '2TB SSD', '1TB HDD', 'RTX 4050 6GB', 16.0, '4K', 2.7, 'Linux', 'Gaming Series', 5.3, 'No', 183000, None)
('LTP00013', 'MSI', 'Business Series', 'Ryzen 5 5500U', '16GB', '512GB SSD', 'None', 'GTX 1650 4GB', 15.6, 'FHD', 1.9, 'Linux', 'Business Series', 7.9, 'Yes', 103000, None)
('LTP00014', 'Dell', 'Notebook', 'i3-1215U', '16GB', '512GB SSD', 'None', 'Integrated', 14.0, 'FHD', 2.1, 'macOS', 'Notebook', 9.4, 'No', 54000, None)
('LTP00015', 'Samsung', 'Gaming Series', 'i7-12700H', '32GB', '1TB SSD', '512GB HDD', 'GTX 1650 4GB', 16.0, 'QHD', 2.0, 'Windows 10', 'Gaming Series', 5.0, 'No', 133000, None)
('LTP00016', 'Infinix', 'Netbook', 'i3-1115G4', '4GB', '256GB HDD', 'None', 'Integrated', 11.6, 'HD', 1.0, 'Windows 11', 'Netbook', 9.7, 'No', 9000, None)
('LTP00017', 'Microsoft', 'Notebook', 'i3-1115G4', '8GB', '512GB SSD', 'None', 'Integrated', 15.6, 'QHD', 1.6, 'Windows 10', 'Notebook', 5.0, 'No', 85000, None)
('LTP00018', 'Samsung', 'Notebook', 'Ryzen 9 5900HS', '8GB', '256GB SSD', 'None', 'Integrated', 14.0, 'FHD', 1.5, 'Windows 11', 'Notebook', 7.9, 'No', 74000, None)
('LTP00019', 'Lenovo', 'Notebook', 'Ryzen 9 5900HX', '4GB', '256GB SSD', 'None', 'Integrated', 14.0, 'FHD', 2.3, 'Windows 10', 'Notebook', 7.8, 'No', 50000, None)
('LTP00020', 'HP', 'Netbook', 'Ryzen 3 3250U', '8GB', '256GB SSD', 'None', 'MX550 2GB', 13.3, 'HD', 1.1, 'DOS', 'Netbook', 8.7, 'No', 34000, None)
('LTP00021', 'HP', 'Notebook', 'i5-1235U', '16GB', '256GB SSD', 'None', 'Integrated', 14.0, 'FHD', 1.8, 'Windows 10', 'Notebook', 5.8, 'No', 67000, None)
('LTP00022', 'Realme', 'Business Series', 'Ryzen 9 5900HX', '16GB', '1TB SSD', '1TB HDD', 'GTX 1650 4GB', 14.0, 'QHD', 1.6, 'Windows 10', 'Business Series', 5.6, 'No', 104000, None)
('LTP00023', 'Acer', 'Notebook', 'i7-12700H', '16GB', '512GB SSD', 'None', 'Integrated', 15.6, 'QHD', 2.2, 'macOS', 'Notebook', 5.5, 'No', 78000, None)
('LTP00024', 'Dell', 'Netbook', 'i3-1115G4', '8GB', '512GB HDD', 'None', 'Integrated', 11.6, 'HD', 1.5, 'macOS', 'Netbook', 8.8, 'No', 26000, None)
('LTP00025', 'Apple', 'Ultrabook', 'Apple M2', '8GB', '256GB SSD', 'None', 'Integrated', 13.3, 'Retina', 1.9, 'macOS', 'Ultrabook', 13.3, 'No', 98000, None)
('LTP00026', 'Microsoft', 'Gaming Series', 'Ryzen 7 5800H', '32GB', '512GB SSD', '1TB HDD', 'RTX 3050 4GB', 15.6, 'FHD', 2.7, 'Windows 11', 'Gaming Series', 5.3, 'No', 148000, None)
('LTP00027', 'Infinix', 'Gaming Series', 'i9-12900H', '16GB', '512GB SSD', '1TB HDD', 'RTX 4060 8GB', 15.6, 'FHD', 2.7, 'Windows 11', 'Gaming Series', 4.0, 'No', 136000, None)
('LTP00028', 'ASUS', 'Notebook', 'i7-12700H', '8GB', '256GB SSD', '512GB HDD', 'MX550 2GB', 15.6, 'FHD', 1.9, 'Linux', 'Notebook', 8.4, 'No', 68000, None)
('LTP00029', 'Dell', 'Notebook', 'i5-11400H', '4GB', '1TB SSD', 'None', 'MX550 2GB', 15.6, 'FHD', 2.3, 'Windows 11', 'Notebook', 5.6, 'No', 58000, None)
('LTP00030', 'Dell', 'Gaming Series', 'i5-12500H', '16GB', '2TB SSD', '2TB HDD', 'RTX 3060 6GB', 17.3, 'FHD', 2.7, 'Windows 11', 'Gaming Series', 5.2, 'No', 123000, None)
('LTP00031', 'MSI', 'Netbook', 'Ryzen 3 3250U', '4GB', '512GB HDD', 'None', 'Integrated', 11.6, 'HD', 1.1, 'macOS', 'Netbook', 8.2, 'Yes', 41000, None)
('LTP00032', 'MSI', 'Gaming Series', 'Ryzen 9 5900HS', '16GB', '2TB SSD', 'None', 'RTX 3070 8GB', 16.0, 'QHD', 2.8, 'macOS', 'Gaming Series', 5.2, 'No', 159000, None)
('LTP00033', 'Avita', 'Ultrabook', 'Ryzen 3 3250U', '16GB', '256GB SSD', 'None', 'Integrated', 13.3, 'HD', 1.2, 'Windows 10', 'Ultrabook', 7.4, 'No', 37000, None)
('LTP00034', 'MSI', 'Gaming Series', 'Ryzen 9 5900HS', '32GB', '1TB SSD', 'None', 'RTX 4060 8GB', 15.6, 'QHD', 2.0, 'Windows 11', 'Gaming Series', 5.3, 'No', 168000, None)
('LTP00035', 'MSI', 'Notebook', 'Ryzen 9 5900HX', '16GB', '256GB SSD', 'None', 'Integrated', 15.6, 'QHD', 2.3, 'Linux', 'Notebook', 8.0, 'No', 112000, None)
('LTP00036', 'Realme', 'Gaming Series', 'Ryzen 9 5900HS', '16GB', '512GB SSD', '1TB HDD', 'RTX 4050 6GB', 16.0, 'FHD', 2.6, 'Linux', 'Gaming Series', 5.5, 'No', 113000, None)
('LTP00037', 'Samsung', 'Ultrabook', 'i5-11400H', '16GB', '256GB SSD', 'None', 'Integrated', 14.0, 'FHD', 1.1, 'Linux', 'Ultrabook', 5.8, 'No', 66000, None)
('LTP00038', 'ASUS', 'Notebook', 'Ryzen 7 5700U', '8GB', '256GB SSD', 'None', 'MX550 2GB', 15.6, '4K', 2.0, 'macOS', 'Notebook', 8.5, 'No', 78000, None)
('LTP00039', 'MSI', 'Ultrabook', 'Ryzen 5 5500U', '16GB', '512GB SSD', 'None', 'MX550 2GB', 13.3, 'FHD', 1.3, 'macOS', 'Ultrabook', 7.4, 'No', 90000, None)
('LTP00040', 'MSI', 'Gaming Series', 'Ryzen 7 5800H', '16GB', '1TB SSD', '512GB HDD', 'RTX 4050 6GB', 17.3, 'FHD', 2.5, 'Windows 11', 'Gaming Series', 3.4, 'No', 124000, None)
('LTP00041', 'MSI', 'Netbook', 'i3-1215U', '8GB', '256GB HDD', 'None', 'MX550 2GB', 13.3, 'HD', 0.9, 'macOS', 'Netbook', 6.1, 'No', 31467, None)
('LTP00042', 'ASUS', 'Ultrabook', 'i3-1215U', '8GB', '256GB SSD', 'None', 'Integrated', 13.3, 'FHD', 1.7, 'Windows 10', 'Ultrabook', 7.8, 'No', 44000, None)
('LTP00043', 'Apple', 'Notebook', 'Apple M1', '16GB', '256GB SSD', '512GB HDD', 'Integrated', 14.0, 'Retina', 2.0, 'macOS', 'Notebook', 17.6, 'No', 117000, None)
('LTP00044', 'MSI', 'Netbook', 'Ryzen 3 3250U', '4GB', '512GB HDD', 'None', 'Integrated', 13.3, 'FHD', 1.3, 'Windows 11', 'Netbook', 6.5, 'No', 45000, None)
('LTP00045', 'Apple', 'Ultrabook', 'Apple M1 Pro', '4GB', '1TB SSD', 'None', 'Integrated', 14.0, 'Retina', 1.8, 'macOS', 'Ultrabook', 12.6, 'No', 123000, None)
('LTP00046', 'Samsung', 'Gaming Series', 'Ryzen 7 5800H', '16GB', '2TB SSD', 'None', 'RTX 4060 8GB', 17.3, 'QHD', 2.4, 'Windows 11', 'Gaming Series', 5.5, 'No', 146000, None)
('LTP00047', 'ASUS', 'Gaming Series', 'i5-12500H', '16GB', '1TB SSD', '512GB HDD', 'RTX 3070 8GB', 17.3, 'FHD', 2.0, 'macOS', 'Gaming Series', 5.6, 'No', 115000, None)
('LTP00048', 'Acer', 'Netbook', 'Ryzen 3 3250U', '4GB', '256GB SSD', 'None', 'Integrated', 13.3, 'HD', 1.4, 'macOS', 'Netbook', 8.8, 'No', 21000, None)
('LTP00049', 'Dell', 'Notebook', 'i9-12900H', '8GB', '1TB SSD', 'None', 'Integrated', 15.6, 'FHD', 2.1, 'Linux', 'Notebook', 6.7, 'No', 84000, None)
('LTP00050', 'Acer', 'Notebook', 'i7-12700H', '16GB', '1TB SSD', 'None', 'Integrated', 14.0, 'FHD', 1.7, 'macOS', 'Notebook', 7.9, 'No', 82000, None)
('LTP00051', 'HP', 'Gaming Series', 'i9-12900H', '16GB', '512GB SSD', '1TB HDD', 'RTX 3060 6GB', 15.6, 'FHD', 2.8, 'Windows 11', 'Gaming Series', 4.7, 'No', 116000, None)
('LTP00052', 'Samsung', 'Notebook', 'i3-1115G4', '8GB', '512GB SSD', 'None', 'MX550 2GB', 14.0, 'FHD', 2.2, 'macOS', 'Notebook', 5.6, 'Yes', 55000, None)
('LTP00053', 'Realme', 'Ultrabook', 'i3-1215U', '16GB', '512GB SSD', 'None', 'Integrated', 13.3, 'HD', 1.8, 'Windows 11', 'Ultrabook', 8.0, 'No', 44000, None)
('LTP00054', 'Microsoft', 'Netbook', 'i3-1215U', '4GB', '512GB HDD', 'None', 'MX550 2GB', 11.6, 'FHD', 1.0, 'macOS', 'Netbook', 6.8, 'No', 49000, None)
('LTP00055', 'Lenovo', 'Ultrabook', 'i7-1255U', '8GB', '1TB SSD', 'None', 'MX550 2GB', 13.3, 'FHD', 1.7, 'Windows 10', 'Ultrabook', 8.5, 'No', 78000, None)
('LTP00056', 'Acer', 'Gaming Series', 'Ryzen 9 5900HX', '16GB', '512GB SSD', '1TB HDD', 'RTX 3070 8GB', 16.0, 'QHD', 2.1, 'Windows 11', 'Gaming Series', 3.5, 'No', 131000, None)
('LTP00057', 'Realme', 'Business Series', 'Ryzen 7 5800H', '16GB', '2TB SSD', 'None', 'MX550 2GB', 15.6, 'FHD', 1.9, 'Windows 10', 'Business Series', 5.4, 'Yes', 87000, None)
('LTP00058', 'Apple', 'Ultrabook', 'Apple M1', '4GB', '1TB SSD', 'None', 'Integrated', 13.3, 'Retina', 2.0, 'macOS', 'Ultrabook', 16.0, 'No', 89000, None)
('LTP00059', 'Lenovo', 'Ultrabook', 'Ryzen 7 5800H', '32GB', '512GB SSD', 'None', 'Integrated', 14.0, 'QHD', 1.5, 'macOS', 'Ultrabook', 7.0, 'No', 90000, None)
('LTP00060', 'Lenovo', 'Netbook', 'Ryzen 3 3250U', '8GB', '256GB HDD', 'None', 'MX550 2GB', 11.6, 'HD', 1.1, 'Linux', 'Netbook', 7.3, 'No', 30000, None)
('LTP00061', 'Microsoft', 'Gaming Series', 'i5-12500H', '8GB', '2TB SSD', 'None', 'RTX 3070 8GB', 16.0, 'QHD', 2.6, 'Linux', 'Gaming Series', 3.6, 'No', 162000, None)
('LTP00062', 'Samsung', 'Gaming Series', 'Ryzen 7 5800H', '64GB', '2TB SSD', '1TB HDD', 'GTX 1650 4GB', 17.3, 'FHD', 2.4, 'Windows 10', 'Gaming Series', 4.7, 'No', 214000, None)
('LTP00063', 'HP', 'Ultrabook', 'i5-1235U', '16GB', '512GB SSD', 'None', 'MX550 2GB', 14.0, 'FHD', 1.5, 'Windows 11', 'Ultrabook', 7.4, 'No', 67000, None)
('LTP00064', 'ASUS', 'Business Series', 'Ryzen 9 5900HX', '8GB', '1TB SSD', 'None', 'Integrated', 15.6, 'QHD', 1.7, 'Windows 11', 'Business Series', 6.5, 'No', 95000, None)
('LTP00065', 'Samsung', 'Gaming Series', 'Ryzen 7 5800H', '16GB', '2TB SSD', 'None', 'RTX 3060 6GB', 16.0, 'QHD', 2.8, 'Linux', 'Gaming Series', 3.7, 'No', 140000, None)
('LTP00066', 'MSI', 'Notebook', 'Ryzen 9 5900HS', '32GB', '1TB SSD', '1TB HDD', 'MX550 2GB', 15.6, '4K', 1.6, 'Linux', 'Notebook', 9.8, 'No', 140000, None)
('LTP00067', 'Samsung', 'Notebook', 'Ryzen 7 5800H', '8GB', '1TB SSD', '512GB HDD', 'Integrated', 14.0, 'FHD', 2.3, 'Windows 10', 'Notebook', 6.7, 'No', 72000, None)
('LTP00068', 'Apple', 'Gaming Series', 'Apple M2 Pro', '64GB', '2TB SSD', '1TB HDD', 'Integrated', 16.0, 'Retina', 2.7, 'macOS', 'Gaming Series', 12.2, 'Yes', 258000, None)
('LTP00069', 'Acer', 'Business Series', 'i5-1135G7', '16GB', '2TB SSD', '1TB HDD', 'Integrated', 15.6, 'HD', 1.7, 'Linux', 'Business Series', 5.1, 'No', 83000, None)
('LTP00070', 'Apple', 'Netbook', 'Apple M2', '4GB', '256GB HDD', 'None', 'Integrated', 11.6, 'Retina', 1.0, 'macOS', 'Netbook', 12.5, 'No', 27891, None)
('LTP00071', 'Samsung', 'Business Series', 'i5-12500H', '16GB', '1TB SSD', 'None', 'MX550 2GB', 14.0, 'FHD', 1.9, 'Windows 11', 'Business Series', 6.4, 'No', 82000, None)
('LTP00072', 'Apple', 'Business Series', 'Apple M1 Pro', '16GB', '1TB SSD', 'None', 'Integrated', 15.6, 'Retina', 2.2, 'macOS', 'Business Series', 13.2, 'No', 143000, None)
('LTP00073', 'ASUS', 'Netbook', 'i3-1215U', '8GB', '256GB HDD', 'None', 'MX550 2GB', 13.3, 'HD', 1.2, 'DOS', 'Netbook', 8.7, 'No', 31000, None)
('LTP00074', 'Realme', 'Gaming Series', 'i9-12900H', '32GB', '512GB SSD', '1TB HDD', 'RTX 4050 6GB', 17.3, 'FHD', 2.6, 'Windows 11', 'Gaming Series', 5.3, 'No', 140000, None)
('LTP00075', 'HP', 'Business Series', 'i3-1215U', '8GB', '1TB SSD', '512GB HDD', 'MX550 2GB', 14.0, 'QHD', 1.8, 'macOS', 'Business Series', 7.1, 'No', 72000, None)
('LTP00076', 'Apple', 'Ultrabook', 'Apple M1 Pro', '16GB', '512GB SSD', 'None', 'Integrated', 14.0, 'Retina', 2.0, 'macOS', 'Ultrabook', 13.8, 'No', 140000, None)
('LTP00077', 'Samsung', 'Business Series', 'i5-12500H', '16GB', '1TB SSD', '2TB HDD', 'GTX 1650 4GB', 15.6, 'HD', 1.8, 'Windows 11', 'Business Series', 6.3, 'No', 99000, None)
('LTP00078', 'Infinix', 'Ultrabook', 'Ryzen 5 5600H', '16GB', '512GB SSD', 'None', 'Integrated', 14.0, 'QHD', 1.2, 'macOS', 'Ultrabook', 5.3, 'No', 60000, None)
('LTP00079', 'Acer', 'Ultrabook', 'i5-1235U', '16GB', '512GB SSD', '1TB HDD', 'Integrated', 13.3, 'HD', 1.9, 'Windows 11', 'Ultrabook', 5.7, 'No', 69000, None)
('LTP00080', 'Infinix', 'Ultrabook', 'Ryzen 7 5700U', '16GB', '512GB SSD', 'None', 'MX550 2GB', 14.0, 'HD', 1.4, 'Windows 11', 'Ultrabook', 7.2, 'No', 63000, None)
('LTP00081', 'HP', 'Business Series', 'Ryzen 5 5500U', '16GB', '512GB SSD', '2TB HDD', 'Integrated', 15.6, 'HD', 1.7, 'macOS', 'Business Series', 8.2, 'No', 64000, None)
('LTP00082', 'Apple', 'Notebook', 'Apple M2', '16GB', '256GB SSD', 'None', 'Integrated', 14.0, 'Retina', 2.0, 'macOS', 'Notebook', 16.9, 'No', 126000, None)
('LTP00083', 'Realme', 'Notebook', 'i5-12500H', '16GB', '256GB SSD', 'None', 'MX550 2GB', 14.0, 'HD', 1.8, 'Windows 11', 'Notebook', 8.9, 'No', 55000, None)
('LTP00084', 'Acer', 'Notebook', 'Ryzen 7 5700U', '8GB', '512GB SSD', 'None', 'Integrated', 14.0, 'FHD', 1.7, 'Windows 10', 'Notebook', 8.1, 'No', 56000, None)
('LTP00085', 'Avita', 'Ultrabook', 'Ryzen 7 5800H', '32GB', '512GB SSD', 'None', 'Integrated', 13.3, 'FHD', 1.9, 'Windows 10', 'Ultrabook', 5.4, 'No', 82000, None)
('LTP00086', 'HP', 'Notebook', 'Ryzen 3 3250U', '8GB', '1TB SSD', 'None', 'MX550 2GB', 14.0, 'FHD', 2.0, 'Linux', 'Notebook', 8.8, 'No', 51000, None)
('LTP00087', 'Samsung', 'Gaming Series', 'Ryzen 7 5800H', '16GB', '2TB SSD', 'None', 'RTX 3070 8GB', 16.0, 'FHD', 2.2, 'macOS', 'Gaming Series', 5.9, 'No', 132000, None)
('LTP00088', 'HP', 'Gaming Series', 'i5-12500H', '32GB', '1TB SSD', '1TB HDD', 'GTX 1650 4GB', 17.3, 'FHD', 2.8, 'Linux', 'Gaming Series', 4.7, 'No', 125000, None)
('LTP00089', 'Avita', 'Business Series', 'Ryzen 7 5700U', '16GB', '1TB SSD', 'None', 'MX550 2GB', 14.0, 'HD', 1.9, 'Windows 10', 'Business Series', 9.2, 'No', 73000, None)
('LTP00090', 'HP', 'Gaming Series', 'Ryzen 9 5900HS', '32GB', '2TB SSD', '1TB HDD', 'RTX 3070 8GB', 17.3, 'FHD', 2.5, 'Windows 11', 'Gaming Series', 5.0, 'No', 152000, None)
('LTP00091', 'Acer', 'Gaming Series', 'i9-12900H', '8GB', '512GB SSD', '512GB HDD', 'RTX 3060 6GB', 16.0, 'FHD', 2.6, 'macOS', 'Gaming Series', 5.9, 'No', 109000, None)
('LTP00092', 'MSI', 'Netbook', 'i3-1215U', '4GB', '256GB HDD', 'None', 'MX550 2GB', 11.6, 'FHD', 1.0, 'Windows 11', 'Netbook', 9.0, 'Yes', 44000, None)
('LTP00093', 'Samsung', 'Ultrabook', 'Ryzen 9 5900HS', '8GB', '1TB SSD', 'None', 'MX550 2GB', 14.0, 'HD', 1.7, 'Linux', 'Ultrabook', 8.0, 'No', 80000, None)
('LTP00094', 'ASUS', 'Netbook', 'Ryzen 3 3250U', '4GB', '256GB SSD', 'None', 'Integrated', 13.3, 'HD', 1.0, 'Windows 10', 'Netbook', 8.0, 'No', 24000, None)
('LTP00095', 'Microsoft', 'Gaming Series', 'Ryzen 9 5900HS', '16GB', '2TB SSD', 'None', 'GTX 1650 4GB', 15.6, 'FHD', 2.1, 'macOS', 'Gaming Series', 3.9, 'No', 142000, None)
('LTP00096', 'Avita', 'Netbook', 'i3-1115G4', '8GB', '256GB SSD', 'None', 'Integrated', 13.3, 'FHD', 1.5, 'Linux', 'Netbook', 6.4, 'No', 18000, None)
('LTP00097', 'Realme', 'Netbook', 'i3-1115G4', '8GB', '256GB SSD', 'None', 'MX550 2GB', 11.6, 'HD', 1.3, 'Linux', 'Netbook', 8.1, 'No', 28000, None)
('LTP00098', 'Apple', 'Gaming Series', 'Apple M2', '16GB', '512GB SSD', 'None', 'Integrated', 15.6, 'Retina', 2.5, 'macOS', 'Gaming Series', 16.6, 'No', 123000, None)
('LTP00099', 'Avita', 'Ultrabook', 'Ryzen 7 5800H', '8GB', '512GB SSD', 'None', 'GTX 1650 4GB', 14.0, 'FHD', 1.8, 'macOS', 'Ultrabook', 8.0, 'No', 51000, None)
('LTP00100', 'Samsung', 'Ultrabook', 'i3-1215U', '4GB', '256GB SSD', 'None', 'MX550 2GB', 14.0, 'FHD', 1.6, 'macOS', 'Ultrabook', 9.0, 'No', 46000, None)
('LTP00101', 'Realme', 'Ultrabook', 'Ryzen 3 3250U', '8GB', '256GB SSD', 'None', 'GTX 1650 4GB', 14.0, 'QHD', 1.1, 'Linux', 'Ultrabook', 8.2, 'Yes', 54000, None)
('LTP00102', 'Samsung', 'Ultrabook', 'i7-1255U', '16GB', '512GB SSD', 'None', 'MX550 2GB', 14.0, 'FHD', 1.1, 'macOS', 'Ultrabook', 8.2, 'No', 86000, None)
('LTP00103', 'Microsoft', 'Ultrabook', 'i7-11800H', '16GB', '1TB SSD', 'None', 'GTX 1650 4GB', 14.0, 'HD', 1.7, 'macOS', 'Ultrabook', 9.6, 'No', 126000, None)
('LTP00104', 'Avita', 'Netbook', 'Ryzen 3 3250U', '4GB', '512GB HDD', 'None', 'MX550 2GB', 11.6, 'HD', 1.4, 'Windows 10', 'Netbook', 9.0, 'No', 15000, None)
('LTP00105', 'Avita', 'Ultrabook', 'Ryzen 9 5900HX', '8GB', '256GB SSD', '512GB HDD', 'Integrated', 14.0, 'QHD', 1.5, 'macOS', 'Ultrabook', 6.1, 'No', 55000, None)
('LTP00106', 'HP', 'Ultrabook', 'Ryzen 9 5900HX', '8GB', '1TB SSD', 'None', 'GTX 1650 4GB', 14.0, 'HD', 1.2, 'Windows 10', 'Ultrabook', 8.5, 'No', 90000, None)
('LTP00107', 'Infinix', 'Netbook', 'i3-1215U', '8GB', '512GB HDD', 'None', 'Integrated', 13.3, 'HD', 1.0, 'macOS', 'Netbook', 9.9, 'No', 15000, None)
('LTP00108', 'ASUS', 'Netbook', 'Ryzen 3 3250U', '8GB', '256GB HDD', 'None', 'MX550 2GB', 13.3, 'FHD', 1.4, 'Linux', 'Netbook', 9.2, 'No', 32000, None)
('LTP00109', 'Avita', 'Ultrabook', 'Ryzen 5 5500U', '16GB', '256GB SSD', 'None', 'GTX 1650 4GB', 13.3, 'FHD', 1.9, 'Windows 10', 'Ultrabook', 5.7, 'No', 63000, None)
('LTP00110', 'ASUS', 'Gaming Series', 'i9-12900H', '8GB', '2TB SSD', 'None', 'RTX 3070 8GB', 16.0, '4K', 2.3, 'Windows 10', 'Gaming Series', 3.1, 'No', 167000, None)
('LTP00111', 'Avita', 'Netbook', 'i3-1115G4', '4GB', '256GB HDD', 'None', 'Integrated', 11.6, 'HD', 1.2, 'Windows 11', 'Netbook', 8.5, 'No', 9000, None)
('LTP00112', 'ASUS', 'Gaming Series', 'Ryzen 9 5900HS', '32GB', '512GB SSD', 'None', 'GTX 1650 4GB', 15.6, 'FHD', 2.5, 'Linux', 'Gaming Series', 4.9, 'Yes', 133000, None)
('LTP00113', 'Samsung', 'Ultrabook', 'i3-1115G4', '8GB', '512GB SSD', 'None', 'GTX 1650 4GB', 14.0, 'FHD', 1.4, 'Windows 11', 'Ultrabook', 8.3, 'No', 68000, None)
('LTP00114', 'HP', 'Business Series', 'Ryzen 9 5900HX', '16GB', '512GB SSD', 'None', 'MX550 2GB', 15.6, 'FHD', 1.5, 'Windows 10', 'Business Series', 8.9, 'No', 91000, None)
('LTP00115', 'Avita', 'Notebook', 'Ryzen 3 3250U', '8GB', '512GB SSD', 'None', 'Integrated', 14.0, 'FHD', 2.0, 'Windows 11', 'Notebook', 9.9, 'No', 30000, None)
('LTP00116', 'Lenovo', 'Notebook', 'Ryzen 7 5800H', '8GB', '256GB SSD', 'None', 'MX550 2GB', 15.6, 'QHD', 1.9, 'Windows 10', 'Notebook', 9.9, 'No', 61000, None)
('LTP00117', 'Avita', 'Notebook', 'Ryzen 5 5500U', '8GB', '512GB SSD', 'None', 'MX550 2GB', 15.6, 'FHD', 2.2, 'Windows 10', 'Notebook', 6.9, 'No', 42000, None)
('LTP00118', 'Samsung', 'Netbook', 'Ryzen 3 3250U', '8GB', '256GB SSD', 'None', 'Integrated', 11.6, 'HD', 1.1, 'macOS', 'Netbook', 6.3, 'No', 36000, None)
('LTP00119', 'Realme', 'Gaming Series', 'i7-12700H', '16GB', '2TB SSD', '1TB HDD', 'RTX 3060 6GB', 16.0, 'QHD', 2.3, 'Linux', 'Gaming Series', 4.9, 'No', 118000, None)
('LTP00120', 'Avita', 'Ultrabook', 'Ryzen 5 5500U', '8GB', '1TB SSD', 'None', 'Integrated', 14.0, 'HD', 1.1, 'Windows 11', 'Ultrabook', 8.9, 'No', 42000, None)
('LTP00121', 'Realme', 'Notebook', 'i5-12500H', '8GB', '256GB SSD', 'None', 'MX550 2GB', 15.6, 'FHD', 2.0, 'Linux', 'Notebook', 6.2, 'No', 51000, None)
('LTP00122', 'Samsung', 'Ultrabook', 'i5-1235U', '16GB', '256GB SSD', '1TB HDD', 'MX550 2GB', 14.0, 'FHD', 2.0, 'macOS', 'Ultrabook', 6.0, 'No', 72000, None)
('LTP00123', 'Lenovo', 'Gaming Series', 'Ryzen 7 5800H', '64GB', '1TB SSD', '1TB HDD', 'RTX 4060 8GB', 17.3, 'FHD', 2.4, 'Windows 10', 'Gaming Series', 5.7, 'No', 205000, None)

In [36]:
cursor.execute("SELECT * FROM laptop_price")
rows = cursor.fetchall()

In [37]:
rows

(('LTP00001',
  'Avita',
  'Notebook',
  'i5-11400H',
  '8GB',
  '256GB SSD',
  'None',
  'Integrated',
  14.0,
  'FHD',
  1.5,
  'Windows 11',
  'Notebook',
  5.5,
  'No',
  42000,
  None),
 ('LTP00002',
  'Microsoft',
  'Notebook',
  'Ryzen 7 5700U',
  '16GB',
  '256GB SSD',
  'None',
  'MX550 2GB',
  14.0,
  'FHD',
  1.8,
  'Windows 11',
  'Notebook',
  5.8,
  'No',
  93000,
  None),
 ('LTP00003',
  'HP',
  'Netbook',
  'i3-1215U',
  '8GB',
  '512GB HDD',
  'None',
  'MX550 2GB',
  11.6,
  'FHD',
  1.1,
  'macOS',
  'Netbook',
  8.2,
  'No',
  33000,
  None),
 ('LTP00004',
  'Apple',
  'Ultrabook',
  'Apple M1',
  '4GB',
  '256GB SSD',
  'None',
  'Integrated',
  13.3,
  'Retina',
  1.9,
  'macOS',
  'Ultrabook',
  17.2,
  'No',
  88000,
  None),
 ('LTP00005',
  'Apple',
  'Notebook',
  'Apple M1 Pro',
  '8GB',
  '512GB SSD',
  'None',
  'Integrated',
  14.0,
  'Retina',
  2.0,
  'macOS',
  'Notebook',
  13.0,
  'No',
  112000,
  None),
 ('LTP00006',
  'MSI',
  'Notebook',
  'i9-12900H',
  '8GB',
  '256GB SSD',
  'None',
  'Integrated',
  15.6,
  'FHD',
  1.7,
  'macOS',
  'Notebook',
  9.7,
  'No',
  95000,
  None),
 ('LTP00007',
  'Avita',
  'Ultrabook',
  'Ryzen 7 5800H',
  '8GB',
  '1TB SSD',
  'None',
  'MX550 2GB',
  14.0,
  'FHD',
  1.4,
  'Windows 11',
  'Ultrabook',
  7.9,
  'No',
  60000,
  None),
 ('LTP00008',
  'Lenovo',
  'Ultrabook',
  'i5-1135G7',
  '8GB',
  '256GB SSD',
  'None',
  'Integrated',
  14.0,
  'FHD',
  1.4,
  'Windows 10',
  'Ultrabook',
  8.0,
  'No',
  48000,
  None),
 ('LTP00009',
  'Microsoft',
  'Gaming Series',
  'i5-12500H',
  '32GB',
  '1TB SSD',
  '1TB HDD',
  'RTX 4060 8GB',
  16.0,
  'FHD',
  2.3,
  'Windows 10',
  'Gaming Series',
  4.4,
  'No',
  185000,
  None),
 ('LTP00010',
  'Acer',
  'Business Series',
  'i7-1255U',
  '8GB',
  '2TB SSD',
  'None',
  'GTX 1650 4GB',
  14.0,
  'HD',
  2.1,
  'Windows 10',
  'Business Series',
  7.7,
  'No',
  99000,
  None),
 ('LTP00011',
  'Dell',
  'Ultrabook',
  'Ryzen 9 5900HS',
  '16GB',
  '512GB SSD',
  'None',
  'Integrated',
  13.3,
  'FHD',
  1.9,
  'Windows 10',
  'Ultrabook',
  5.4,
  'No',
  72000,
  None),
 ('LTP00012',
  'Microsoft',
  'Gaming Series',
  'i7-12700H',
  '16GB',
  '2TB SSD',
  '1TB HDD',
  'RTX 4050 6GB',
  16.0,
  '4K',
  2.7,
  'Linux',
  'Gaming Series',
  5.3,
  'No',
  183000,
  None),
 ('LTP00013',
  'MSI',
  'Business Series',
  'Ryzen 5 5500U',
  '16GB',
  '512GB SSD',
  'None',
  'GTX 1650 4GB',
  15.6,
  'FHD',
  1.9,
  'Linux',
  'Business Series',
  7.9,
  'Yes',
  103000,
  None),
 ('LTP00014',
  'Dell',
  'Notebook',
  'i3-1215U',
  '16GB',
  '512GB SSD',
  'None',
  'Integrated',
  14.0,
  'FHD',
  2.1,
  'macOS',
  'Notebook',
  9.4,
  'No',
  54000,
  None),
 ('LTP00015',
  'Samsung',
  'Gaming Series',
  'i7-12700H',
  '32GB',
  '1TB SSD',
  '512GB HDD',
  'GTX 1650 4GB',
  16.0,
  'QHD',
  2.0,
  'Windows 10',
  'Gaming Series',
  5.0,
  'No',
  133000,
  None),
 ('LTP00016',
  'Infinix',
  'Netbook',
  'i3-1115G4',
  '4GB',
  '256GB HDD',
  'None',
  'Integrated',
  11.6,
  'HD',
  1.0,
  'Windows 11',
  'Netbook',
  9.7,
  'No',
  9000,
  None),
 ('LTP00017',
  'Microsoft',
  'Notebook',
  'i3-1115G4',
  '8GB',
  '512GB SSD',
  'None',
  'Integrated',
  15.6,
  'QHD',
  1.6,
  'Windows 10',
  'Notebook',
  5.0,
  'No',
  85000,
  None),
 ('LTP00018',
  'Samsung',
  'Notebook',
  'Ryzen 9 5900HS',
  '8GB',
  '256GB SSD',
  'None',
  'Integrated',
  14.0,
  'FHD',
  1.5,
  'Windows 11',
  'Notebook',
  7.9,
  'No',
  74000,
  None),
 ('LTP00019',
  'Lenovo',
  'Notebook',
  'Ryzen 9 5900HX',
  '4GB',
  '256GB SSD',
  'None',
  'Integrated',
  14.0,
  'FHD',
  2.3,
  'Windows 10',
  'Notebook',
  7.8,
  'No',
  50000,
  None),
 ('LTP00020',
  'HP',
  'Netbook',
  'Ryzen 3 3250U',
  '8GB',
  '256GB SSD',
  'None',
  'MX550 2GB',
  13.3,
  'HD',
  1.1,
  'DOS',
  'Netbook',
  8.7,
  'No',
  34000,
  None),
 ('LTP00021',
  'HP',
  'Notebook',
  'i5-1235U',
  '16GB',
  '256GB SSD',
  'None',
  'Integrated',
  14.0,
  'FHD',
  1.8,
  'Windows 10',
  'Notebook',
  5.8,
  'No',
  67000,
  None),
 ('LTP00022',
  'Realme',
  'Business Series',
  'Ryzen 9 5900HX',
  '16GB',
  '1TB SSD',
  '1TB HDD',
  'GTX 1650 4GB',
  14.0,
  'QHD',
  1.6,
  'Windows 10',
  'Business Series',
  5.6,
  'No',
  104000,
  None),
 ('LTP00023',
  'Acer',
  'Notebook',
  'i7-12700H',
  '16GB',
  '512GB SSD',
  'None',
  'Integrated',
  15.6,
  'QHD',
  2.2,
  'macOS',
  'Notebook',
  5.5,
  'No',
  78000,
  None),
 ('LTP00024',
  'Dell',
  'Netbook',
  'i3-1115G4',
  '8GB',
  '512GB HDD',
  'None',
  'Integrated',
  11.6,
  'HD',
  1.5,
  'macOS',
  'Netbook',
  8.8,
  'No',
  26000,
  None),
 ('LTP00025',
  'Apple',
  'Ultrabook',
  'Apple M2',
  '8GB',
  '256GB SSD',
  'None',
  'Integrated',
  13.3,
  'Retina',
  1.9,
  'macOS',
  'Ultrabook',
  13.3,
  'No',
  98000,
  None),
 ('LTP00026',
  'Microsoft',
  'Gaming Series',
  'Ryzen 7 5800H',
  '32GB',
  '512GB SSD',
  '1TB HDD',
  'RTX 3050 4GB',
  15.6,
  'FHD',
  2.7,
  'Windows 11',
  'Gaming Series',
  5.3,
  'No',
  148000,
  None),
 ('LTP00027',
  'Infinix',
  'Gaming Series',
  'i9-12900H',
  '16GB',
  '512GB SSD',
  '1TB HDD',
  'RTX 4060 8GB',
  15.6,
  'FHD',
  2.7,
  'Windows 11',
  'Gaming Series',
  4.0,
  'No',
  136000,
  None),
 ('LTP00028',
  'ASUS',
  'Notebook',
  'i7-12700H',
  '8GB',
  '256GB SSD',
  '512GB HDD',
  'MX550 2GB',
  15.6,
  'FHD',
  1.9,
  'Linux',
  'Notebook',
  8.4,
  'No',
  68000,
  None),
 ('LTP00029',
  'Dell',
  'Notebook',
  'i5-11400H',
  '4GB',
  '1TB SSD',
  'None',
  'MX550 2GB',
  15.6,
  'FHD',
  2.3,
  'Windows 11',
  'Notebook',
  5.6,
  'No',
  58000,
  None),
 ('LTP00030',
  'Dell',
  'Gaming Series',
  'i5-12500H',
  '16GB',
  '2TB SSD',
  '2TB HDD',
  'RTX 3060 6GB',
  17.3,
  'FHD',
  2.7,
  'Windows 11',
  'Gaming Series',
  5.2,
  'No',
  123000,
  None),
 ('LTP00031',
  'MSI',
  'Netbook',
  'Ryzen 3 3250U',
  '4GB',
  '512GB HDD',
  'None',
  'Integrated',
  11.6,
  'HD',
  1.1,
  'macOS',
  'Netbook',
  8.2,
  'Yes',
  41000,
  None),
 ('LTP00032',
  'MSI',
  'Gaming Series',
  'Ryzen 9 5900HS',
  '16GB',
  '2TB SSD',
  'None',
  'RTX 3070 8GB',
  16.0,
  'QHD',
  2.8,
  'macOS',
  'Gaming Series',
  5.2,
  'No',
  159000,
  None),
 ('LTP00033',
  'Avita',
  'Ultrabook',
  'Ryzen 3 3250U',
  '16GB',
  '256GB SSD',
  'None',
  'Integrated',
  13.3,
  'HD',
  1.2,
  'Windows 10',
  'Ultrabook',
  7.4,
  'No',
  37000,
  None),
 ('LTP00034',
  'MSI',
  'Gaming Series',
  'Ryzen 9 5900HS',
  '32GB',
  '1TB SSD',
  'None',
  'RTX 4060 8GB',
  15.6,
  'QHD',
  2.0,
  'Windows 11',
  'Gaming Series',
  5.3,
  'No',
  168000,
  None),
 ('LTP00035',
  'MSI',
  'Notebook',
  'Ryzen 9 5900HX',
  '16GB',
  '256GB SSD',
  'None',
  'Integrated',
  15.6,
  'QHD',
  2.3,
  'Linux',
  'Notebook',
  8.0,
  'No',
  112000,
  None),
 ('LTP00036',
  'Realme',
  'Gaming Series',
  'Ryzen 9 5900HS',
  '16GB',
  '512GB SSD',
  '1TB HDD',
  'RTX 4050 6GB',
  16.0,
  'FHD',
  2.6,
  'Linux',
  'Gaming Series',
  5.5,
  'No',
  113000,
  None),
 ('LTP00037',
  'Samsung',
  'Ultrabook',
  'i5-11400H',
  '16GB',
  '256GB SSD',
  'None',
  'Integrated',
  14.0,
  'FHD',
  1.1,
  'Linux',
  'Ultrabook',
  5.8,
  'No',
  66000,
  None),
 ('LTP00038',
  'ASUS',
  'Notebook',
  'Ryzen 7 5700U',
  '8GB',
  '256GB SSD',
  'None',
  'MX550 2GB',
  15.6,
  '4K',
  2.0,
  'macOS',
  'Notebook',
  8.5,
  'No',
  78000,
  None),
 ('LTP00039',
  'MSI',
  'Ultrabook',
  'Ryzen 5 5500U',
  '16GB',
  '512GB SSD',
  'None',
  'MX550 2GB',
  13.3,
  'FHD',
  1.3,
  'macOS',
  'Ultrabook',
  7.4,
  'No',
  90000,
  None),
 ('LTP00040',
  'MSI',
  'Gaming Series',
  'Ryzen 7 5800H',
  '16GB',
  '1TB SSD',
  '512GB HDD',
  'RTX 4050 6GB',
  17.3,
  'FHD',
  2.5,
  'Windows 11',
  'Gaming Series',
  3.4,
  'No',
  124000,
  None),
 ('LTP00041',
  'MSI',
  'Netbook',
  'i3-1215U',
  '8GB',
  '256GB HDD',
  'None',
  'MX550 2GB',
  13.3,
  'HD',
  0.9,
  'macOS',
  'Netbook',
  6.1,
  'No',
  31467,
  None),
 ('LTP00042',
  'ASUS',
  'Ultrabook',
  'i3-1215U',
  '8GB',
  '256GB SSD',
  'None',
  'Integrated',
  13.3,
  'FHD',
  1.7,
  'Windows 10',
  'Ultrabook',
  7.8,
  'No',
  44000,
  None),
 ('LTP00043',
  'Apple',
  'Notebook',
  'Apple M1',
  '16GB',
  '256GB SSD',
  '512GB HDD',
  'Integrated',
  14.0,
  'Retina',
  2.0,
  'macOS',
  'Notebook',
  17.6,
  'No',
  117000,
  None),
 ('LTP00044',
  'MSI',
  'Netbook',
  'Ryzen 3 3250U',
  '4GB',
  '512GB HDD',
  'None',
  'Integrated',
  13.3,
  'FHD',
  1.3,
  'Windows 11',
  'Netbook',
  6.5,
  'No',
  45000,
  None),
 ('LTP00045',
  'Apple',
  'Ultrabook',
  'Apple M1 Pro',
  '4GB',
  '1TB SSD',
  'None',
  'Integrated',
  14.0,
  'Retina',
  1.8,
  'macOS',
  'Ultrabook',
  12.6,
  'No',
  123000,
  None),
 ('LTP00046',
  'Samsung',
  'Gaming Series',
  'Ryzen 7 5800H',
  '16GB',
  '2TB SSD',
  'None',
  'RTX 4060 8GB',
  17.3,
  'QHD',
  2.4,
  'Windows 11',
  'Gaming Series',
  5.5,
  'No',
  146000,
  None),
 ('LTP00047',
  'ASUS',
  'Gaming Series',
  'i5-12500H',
  '16GB',
  '1TB SSD',
  '512GB HDD',
  'RTX 3070 8GB',
  17.3,
  'FHD',
  2.0,
  'macOS',
  'Gaming Series',
  5.6,
  'No',
  115000,
  None),
 ('LTP00048',
  'Acer',
  'Netbook',
  'Ryzen 3 3250U',
  '4GB',
  '256GB SSD',
  'None',
  'Integrated',
  13.3,
  'HD',
  1.4,
  'macOS',
  'Netbook',
  8.8,
  'No',
  21000,
  None),
 ('LTP00049',
  'Dell',
  'Notebook',
  'i9-12900H',
  '8GB',
  '1TB SSD',
  'None',
  'Integrated',
  15.6,
  'FHD',
  2.1,
  'Linux',
  'Notebook',
  6.7,
  'No',
  84000,
  None),
 ('LTP00050',
  'Acer',
  'Notebook',
  'i7-12700H',
  '16GB',
  '1TB SSD',
  'None',
  'Integrated',
  14.0,
  'FHD',
  1.7,
  'macOS',
  'Notebook',
  7.9,
  'No',
  82000,
  None),
 ('LTP00051',
  'HP',
  'Gaming Series',
  'i9-12900H',
  '16GB',
  '512GB SSD',
  '1TB HDD',
  'RTX 3060 6GB',
  15.6,
  'FHD',
  2.8,
  'Windows 11',
  'Gaming Series',
  4.7,
  'No',
  116000,
  None),
 ('LTP00052',
  'Samsung',
  'Notebook',
  'i3-1115G4',
  '8GB',
  '512GB SSD',
  'None',
  'MX550 2GB',
  14.0,
  'FHD',
  2.2,
  'macOS',
  'Notebook',
  5.6,
  'Yes',
  55000,
  None),
 ('LTP00053',
  'Realme',
  'Ultrabook',
  'i3-1215U',
  '16GB',
  '512GB SSD',
  'None',
  'Integrated',
  13.3,
  'HD',
  1.8,
  'Windows 11',
  'Ultrabook',
  8.0,
  'No',
  44000,
  None),
 ('LTP00054',
  'Microsoft',
  'Netbook',
  'i3-1215U',
  '4GB',
  '512GB HDD',
  'None',
  'MX550 2GB',
  11.6,
  'FHD',
  1.0,
  'macOS',
  'Netbook',
  6.8,
  'No',
  49000,
  None),
 ('LTP00055',
  'Lenovo',
  'Ultrabook',
  'i7-1255U',
  '8GB',
  '1TB SSD',
  'None',
  'MX550 2GB',
  13.3,
  'FHD',
  1.7,
  'Windows 10',
  'Ultrabook',
  8.5,
  'No',
  78000,
  None),
 ('LTP00056',
  'Acer',
  'Gaming Series',
  'Ryzen 9 5900HX',
  '16GB',
  '512GB SSD',
  '1TB HDD',
  'RTX 3070 8GB',
  16.0,
  'QHD',
  2.1,
  'Windows 11',
  'Gaming Series',
  3.5,
  'No',
  131000,
  None),
 ('LTP00057',
  'Realme',
  'Business Series',
  'Ryzen 7 5800H',
  '16GB',
  '2TB SSD',
  'None',
  'MX550 2GB',
  15.6,
  'FHD',
  1.9,
  'Windows 10',
  'Business Series',
  5.4,
  'Yes',
  87000,
  None),
 ('LTP00058',
  'Apple',
  'Ultrabook',
  'Apple M1',
  '4GB',
  '1TB SSD',
  'None',
  'Integrated',
  13.3,
  'Retina',
  2.0,
  'macOS',
  'Ultrabook',
  16.0,
  'No',
  89000,
  None),
 ('LTP00059',
  'Lenovo',
  'Ultrabook',
  'Ryzen 7 5800H',
  '32GB',
  '512GB SSD',
  'None',
  'Integrated',
  14.0,
  'QHD',
  1.5,
  'macOS',
  'Ultrabook',
  7.0,
  'No',
  90000,
  None),
 ('LTP00060',
  'Lenovo',
  'Netbook',
  'Ryzen 3 3250U',
  '8GB',
  '256GB HDD',
  'None',
  'MX550 2GB',
  11.6,
  'HD',
  1.1,
  'Linux',
  'Netbook',
  7.3,
  'No',
  30000,
  None),
 ('LTP00061',
  'Microsoft',
  'Gaming Series',
  'i5-12500H',
  '8GB',
  '2TB SSD',
  'None',
  'RTX 3070 8GB',
  16.0,
  'QHD',
  2.6,
  'Linux',
  'Gaming Series',
  3.6,
  'No',
  162000,
  None),
 ('LTP00062',
  'Samsung',
  'Gaming Series',
  'Ryzen 7 5800H',
  '64GB',
  '2TB SSD',
  '1TB HDD',
  'GTX 1650 4GB',
  17.3,
  'FHD',
  2.4,
  'Windows 10',
  'Gaming Series',
  4.7,
  'No',
  214000,
  None),
 ('LTP00063',
  'HP',
  'Ultrabook',
  'i5-1235U',
  '16GB',
  '512GB SSD',
  'None',
  'MX550 2GB',
  14.0,
  'FHD',
  1.5,
  'Windows 11',
  'Ultrabook',
  7.4,
  'No',
  67000,
  None),
 ('LTP00064',
  'ASUS',
  'Business Series',
  'Ryzen 9 5900HX',
  '8GB',
  '1TB SSD',
  'None',
  'Integrated',
  15.6,
  'QHD',
  1.7,
  'Windows 11',
  'Business Series',
  6.5,
  'No',
  95000,
  None),
 ('LTP00065',
  'Samsung',
  'Gaming Series',
  'Ryzen 7 5800H',
  '16GB',
  '2TB SSD',
  'None',
  'RTX 3060 6GB',
  16.0,
  'QHD',
  2.8,
  'Linux',
  'Gaming Series',
  3.7,
  'No',
  140000,
  None),
 ('LTP00066',
  'MSI',
  'Notebook',
  'Ryzen 9 5900HS',
  '32GB',
  '1TB SSD',
  '1TB HDD',
  'MX550 2GB',
  15.6,
  '4K',
  1.6,
  'Linux',
  'Notebook',
  9.8,
  'No',
  140000,
  None),
 ('LTP00067',
  'Samsung',
  'Notebook',
  'Ryzen 7 5800H',
  '8GB',
  '1TB SSD',
  '512GB HDD',
  'Integrated',
  14.0,
  'FHD',
  2.3,
  'Windows 10',
  'Notebook',
  6.7,
  'No',
  72000,
  None),
 ('LTP00068',
  'Apple',
  'Gaming Series',
  'Apple M2 Pro',
  '64GB',
  '2TB SSD',
  '1TB HDD',
  'Integrated',
  16.0,
  'Retina',
  2.7,
  'macOS',
  'Gaming Series',
  12.2,
  'Yes',
  258000,
  None),
 ('LTP00069',
  'Acer',
  'Business Series',
  'i5-1135G7',
  '16GB',
  '2TB SSD',
  '1TB HDD',
  'Integrated',
  15.6,
  'HD',
  1.7,
  'Linux',
  'Business Series',
  5.1,
  'No',
  83000,
  None),
 ('LTP00070',
  'Apple',
  'Netbook',
  'Apple M2',
  '4GB',
  '256GB HDD',
  'None',
  'Integrated',
  11.6,
  'Retina',
  1.0,
  'macOS',
  'Netbook',
  12.5,
  'No',
  27891,
  None),
 ('LTP00071',
  'Samsung',
  'Business Series',
  'i5-12500H',
  '16GB',
  '1TB SSD',
  'None',
  'MX550 2GB',
  14.0,
  'FHD',
  1.9,
  'Windows 11',
  'Business Series',
  6.4,
  'No',
  82000,
  None),
 ('LTP00072',
  'Apple',
  'Business Series',
  'Apple M1 Pro',
  '16GB',
  '1TB SSD',
  'None',
  'Integrated',
  15.6,
  'Retina',
  2.2,
  'macOS',
  'Business Series',
  13.2,
  'No',
  143000,
  None),
 ('LTP00073',
  'ASUS',
  'Netbook',
  'i3-1215U',
  '8GB',
  '256GB HDD',
  'None',
  'MX550 2GB',
  13.3,
  'HD',
  1.2,
  'DOS',
  'Netbook',
  8.7,
  'No',
  31000,
  None),
 ('LTP00074',
  'Realme',
  'Gaming Series',
  'i9-12900H',
  '32GB',
  '512GB SSD',
  '1TB HDD',
  'RTX 4050 6GB',
  17.3,
  'FHD',
  2.6,
  'Windows 11',
  'Gaming Series',
  5.3,
  'No',
  140000,
  None),
 ('LTP00075',
  'HP',
  'Business Series',
  'i3-1215U',
  '8GB',
  '1TB SSD',
  '512GB HDD',
  'MX550 2GB',
  14.0,
  'QHD',
  1.8,
  'macOS',
  'Business Series',
  7.1,
  'No',
  72000,
  None),
 ('LTP00076',
  'Apple',
  'Ultrabook',
  'Apple M1 Pro',
  '16GB',
  '512GB SSD',
  'None',
  'Integrated',
  14.0,
  'Retina',
  2.0,
  'macOS',
  'Ultrabook',
  13.8,
  'No',
  140000,
  None),
 ('LTP00077',
  'Samsung',
  'Business Series',
  'i5-12500H',
  '16GB',
  '1TB SSD',
  '2TB HDD',
  'GTX 1650 4GB',
  15.6,
  'HD',
  1.8,
  'Windows 11',
  'Business Series',
  6.3,
  'No',
  99000,
  None),
 ('LTP00078',
  'Infinix',
  'Ultrabook',
  'Ryzen 5 5600H',
  '16GB',
  '512GB SSD',
  'None',
  'Integrated',
  14.0,
  'QHD',
  1.2,
  'macOS',
  'Ultrabook',
  5.3,
  'No',
  60000,
  None),
 ('LTP00079',
  'Acer',
  'Ultrabook',
  'i5-1235U',
  '16GB',
  '512GB SSD',
  '1TB HDD',
  'Integrated',
  13.3,
  'HD',
  1.9,
  'Windows 11',
  'Ultrabook',
  5.7,
  'No',
  69000,
  None),
 ('LTP00080',
  'Infinix',
  'Ultrabook',
  'Ryzen 7 5700U',
  '16GB',
  '512GB SSD',
  'None',
  'MX550 2GB',
  14.0,
  'HD',
  1.4,
  'Windows 11',
  'Ultrabook',
  7.2,
  'No',
  63000,
  None),
 ('LTP00081',
  'HP',
  'Business Series',
  'Ryzen 5 5500U',
  '16GB',
  '512GB SSD',
  '2TB HDD',
  'Integrated',
  15.6,
  'HD',
  1.7,
  'macOS',
  'Business Series',
  8.2,
  'No',
  64000,
  None),
 ('LTP00082',
  'Apple',
  'Notebook',
  'Apple M2',
  '16GB',
  '256GB SSD',
  'None',
  'Integrated',
  14.0,
  'Retina',
  2.0,
  'macOS',
  'Notebook',
  16.9,
  'No',
  126000,
  None),
 ('LTP00083',
  'Realme',
  'Notebook',
  'i5-12500H',
  '16GB',
  '256GB SSD',
  'None',
  'MX550 2GB',
  14.0,
  'HD',
  1.8,
  'Windows 11',
  'Notebook',
  8.9,
  'No',
  55000,
  None),
 ('LTP00084',
  'Acer',
  'Notebook',
  'Ryzen 7 5700U',
  '8GB',
  '512GB SSD',
  'None',
  'Integrated',
  14.0,
  'FHD',
  1.7,
  'Windows 10',
  'Notebook',
  8.1,
  'No',
  56000,
  None),
 ('LTP00085',
  'Avita',
  'Ultrabook',
  'Ryzen 7 5800H',
  '32GB',
  '512GB SSD',
  'None',
  'Integrated',
  13.3,
  'FHD',
  1.9,
  'Windows 10',
  'Ultrabook',
  5.4,
  'No',
  82000,
  None),
 ('LTP00086',
  'HP',
  'Notebook',
  'Ryzen 3 3250U',
  '8GB',
  '1TB SSD',
  'None',
  'MX550 2GB',
  14.0,
  'FHD',
  2.0,
  'Linux',
  'Notebook',
  8.8,
  'No',
  51000,
  None),
 ('LTP00087',
  'Samsung',
  'Gaming Series',
  'Ryzen 7 5800H',
  '16GB',
  '2TB SSD',
  'None',
  'RTX 3070 8GB',
  16.0,
  'FHD',
  2.2,
  'macOS',
  'Gaming Series',
  5.9,
  'No',
  132000,
  None),
 ('LTP00088',
  'HP',
  'Gaming Series',
  'i5-12500H',
  '32GB',
  '1TB SSD',
  '1TB HDD',
  'GTX 1650 4GB',
  17.3,
  'FHD',
  2.8,
  'Linux',
  'Gaming Series',
  4.7,
  'No',
  125000,
  None),
 ('LTP00089',
  'Avita',
  'Business Series',
  'Ryzen 7 5700U',
  '16GB',
  '1TB SSD',
  'None',
  'MX550 2GB',
  14.0,
  'HD',
  1.9,
  'Windows 10',
  'Business Series',
  9.2,
  'No',
  73000,
  None),
 ('LTP00090',
  'HP',
  'Gaming Series',
  'Ryzen 9 5900HS',
  '32GB',
  '2TB SSD',
  '1TB HDD',
  'RTX 3070 8GB',
  17.3,
  'FHD',
  2.5,
  'Windows 11',
  'Gaming Series',
  5.0,
  'No',
  152000,
  None),
 ('LTP00091',
  'Acer',
  'Gaming Series',
  'i9-12900H',
  '8GB',
  '512GB SSD',
  '512GB HDD',
  'RTX 3060 6GB',
  16.0,
  'FHD',
  2.6,
  'macOS',
  'Gaming Series',
  5.9,
  'No',
  109000,
  None),
 ('LTP00092',
  'MSI',
  'Netbook',
  'i3-1215U',
  '4GB',
  '256GB HDD',
  'None',
  'MX550 2GB',
  11.6,
  'FHD',
  1.0,
  'Windows 11',
  'Netbook',
  9.0,
  'Yes',
  44000,
  None),
 ('LTP00093',
  'Samsung',
  'Ultrabook',
  'Ryzen 9 5900HS',
  '8GB',
  '1TB SSD',
  'None',
  'MX550 2GB',
  14.0,
  'HD',
  1.7,
  'Linux',
  'Ultrabook',
  8.0,
  'No',
  80000,
  None),
 ('LTP00094',
  'ASUS',
  'Netbook',
  'Ryzen 3 3250U',
  '4GB',
  '256GB SSD',
  'None',
  'Integrated',
  13.3,
  'HD',
  1.0,
  'Windows 10',
  'Netbook',
  8.0,
  'No',
  24000,
  None),
 ('LTP00095',
  'Microsoft',
  'Gaming Series',
  'Ryzen 9 5900HS',
  '16GB',
  '2TB SSD',
  'None',
  'GTX 1650 4GB',
  15.6,
  'FHD',
  2.1,
  'macOS',
  'Gaming Series',
  3.9,
  'No',
  142000,
  None),
 ('LTP00096',
  'Avita',
  'Netbook',
  'i3-1115G4',
  '8GB',
  '256GB SSD',
  'None',
  'Integrated',
  13.3,
  'FHD',
  1.5,
  'Linux',
  'Netbook',
  6.4,
  'No',
  18000,
  None),
 ('LTP00097',
  'Realme',
  'Netbook',
  'i3-1115G4',
  '8GB',
  '256GB SSD',
  'None',
  'MX550 2GB',
  11.6,
  'HD',
  1.3,
  'Linux',
  'Netbook',
  8.1,
  'No',
  28000,
  None),
 ('LTP00098',
  'Apple',
  'Gaming Series',
  'Apple M2',
  '16GB',
  '512GB SSD',
  'None',
  'Integrated',
  15.6,
  'Retina',
  2.5,
  'macOS',
  'Gaming Series',
  16.6,
  'No',
  123000,
  None),
 ('LTP00099',
  'Avita',
  'Ultrabook',
  'Ryzen 7 5800H',
  '8GB',
  '512GB SSD',
  'None',
  'GTX 1650 4GB',
  14.0,
  'FHD',
  1.8,
  'macOS',
  'Ultrabook',
  8.0,
  'No',
  51000,
  None),
 ('LTP00100',
  'Samsung',
  'Ultrabook',
  'i3-1215U',
  '4GB',
  '256GB SSD',
  'None',
  'MX550 2GB',
  14.0,
  'FHD',
  1.6,
  'macOS',
  'Ultrabook',
  9.0,
  'No',
  46000,
  None),
 ('LTP00101',
  'Realme',
  'Ultrabook',
  'Ryzen 3 3250U',
  '8GB',
  '256GB SSD',
  'None',
  'GTX 1650 4GB',
  14.0,
  'QHD',
  1.1,
  'Linux',
  'Ultrabook',
  8.2,
  'Yes',
  54000,
  None),
 ('LTP00102',
  'Samsung',
  'Ultrabook',
  'i7-1255U',
  '16GB',
  '512GB SSD',
  'None',
  'MX550 2GB',
  14.0,
  'FHD',
  1.1,
  'macOS',
  'Ultrabook',
  8.2,
  'No',
  86000,
  None),

In [38]:
import pandas as pd

In [39]:
columns = [col[0] for col in cursor.description]
df = pd.DataFrame(rows, columns=columns)

In [42]:
columns

['SKU',
 'Brand',
 'Model',
 'CPU',
 'RAM',
 'Primary_Storage',
 'Secondary_Storage',
 'GPU',
 'Screen_Size',
 'Resolution',
 'Weight_kg',
 'OS',
 'Type',
 'Battery_Hours',
 'Touchscreen',
 'Price_INR',
 'price_cat']

In [40]:
df.head()

,SKU,Brand,Model,CPU,RAM,Primary_Storage,Secondary_Storage,GPU,Screen_Size,Resolution,Weight_kg,OS,Type,Battery_Hours,Touchscreen,Price_INR,price_cat
0,LTP00001,Avita,Notebook,i5-11400H,8GB,256GB SSD,None,Integrated,14.0,FHD,1.5,Windows 11,Notebook,5.5,No,42000,None
1,LTP00002,Microsoft,Notebook,Ryzen 7 5700U,16GB,256GB SSD,None,MX550 2GB,14.0,FHD,1.8,Windows 11,Notebook,5.8,No,93000,None
2,LTP00003,HP,Netbook,i3-1215U,8GB,512GB HDD,None,MX550 2GB,11.6,FHD,1.1,macOS,Netbook,8.2,No,33000,None
3,LTP00004,Apple,Ultrabook,Apple M1,4GB,256GB SSD,None,Integrated,13.3,Retina,1.9,macOS,Ultrabook,17.2,No,88000,None
4,LTP00005,Apple,Notebook,Apple M1 Pro,8GB,512GB SSD,None,Integrated,14.0,Retina,2.0,macOS,Notebook,13.0,No,112000,None

In [41]:
df.shape

(5000, 17)

In [48]:
# ---- A. Read the CSV File ----
csv_path = "F:\\01. The Data Psychology\\4. New_Machine_Learning\\laptop price prediction\\31. Laptop_CSV_File.csv"
df1 = pd.read_csv(csv_path)

In [49]:
df1.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [45]:
df1.shape

(1303, 12)

In [50]:
# Optional: Rename 'Unnamed: 0' column to 'id' for clarity
df1= df1.iloc[:,1:]

In [51]:
df1.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [52]:
cursor.execute("use newdb")

0

In [53]:
create_table_query = """
CREATE TABLE IF NOT EXISTS laptops (
    Company VARCHAR(255),
    TypeName VARCHAR(255),
    Inches FLOAT,
    ScreenResolution VARCHAR(255),
    Cpu VARCHAR(255),
    Ram VARCHAR(20),
    Memory VARCHAR(255),
    Gpu VARCHAR(255),
    OpSys VARCHAR(255),
    Weight VARCHAR(20),
    Price FLOAT
)
"""

In [54]:
cursor.execute(create_table_query)

0

In [55]:
insert_query = """
INSERT INTO laptops (Company, TypeName, Inches, ScreenResolution, Cpu, Ram, Memory, Gpu, OpSys, Weight, Price)
VALUES ( %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE 
    Company=VALUES(Company), TypeName=VALUES(TypeName), Inches=VALUES(Inches),
    ScreenResolution=VALUES(ScreenResolution), Cpu=VALUES(Cpu), Ram=VALUES(Ram),
    Memory=VALUES(Memory), Gpu=VALUES(Gpu), OpSys=VALUES(OpSys), Weight=VALUES(Weight), Price=VALUES(Price)
"""

In [56]:
data_tuples = [tuple(row) for row in df1.values]

In [57]:
data_tuples

[('Apple',
  'Ultrabook',
  13.3,
  'IPS Panel Retina Display 2560x1600',
  'Intel Core i5 2.3GHz',
  '8GB',
  '128GB SSD',
  'Intel Iris Plus Graphics 640',
  'macOS',
  '1.37kg',
  71378.6832),
 ('Apple',
  'Ultrabook',
  13.3,
  '1440x900',
  'Intel Core i5 1.8GHz',
  '8GB',
  '128GB Flash Storage',
  'Intel HD Graphics 6000',
  'macOS',
  '1.34kg',
  47895.5232),
 ('HP',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i5 7200U 2.5GHz',
  '8GB',
  '256GB SSD',
  'Intel HD Graphics 620',
  'No OS',
  '1.86kg',
  30636.0),
 ('Apple',
  'Ultrabook',
  15.4,
  'IPS Panel Retina Display 2880x1800',
  'Intel Core i7 2.7GHz',
  '16GB',
  '512GB SSD',
  'AMD Radeon Pro 455',
  'macOS',
  '1.83kg',
  135195.336),
 ('Apple',
  'Ultrabook',
  13.3,
  'IPS Panel Retina Display 2560x1600',
  'Intel Core i5 3.1GHz',
  '8GB',
  '256GB SSD',
  'Intel Iris Plus Graphics 650',
  'macOS',
  '1.37kg',
  96095.808),
 ('Acer',
  'Notebook',
  15.6,
  '1366x768',
  'AMD A9-Series 9420 3GHz',
  '4GB',
  '500GB HDD',
  'AMD Radeon R5',
  'Windows 10',
  '2.1kg',
  21312.0),
 ('Apple',
  'Ultrabook',
  15.4,
  'IPS Panel Retina Display 2880x1800',
  'Intel Core i7 2.2GHz',
  '16GB',
  '256GB Flash Storage',
  'Intel Iris Pro Graphics',
  'Mac OS X',
  '2.04kg',
  114017.6016),
 ('Apple',
  'Ultrabook',
  13.3,
  '1440x900',
  'Intel Core i5 1.8GHz',
  '8GB',
  '256GB Flash Storage',
  'Intel HD Graphics 6000',
  'macOS',
  '1.34kg',
  61735.536),
 ('Asus',
  'Ultrabook',
  14.0,
  'Full HD 1920x1080',
  'Intel Core i7 8550U 1.8GHz',
  '16GB',
  '512GB SSD',
  'Nvidia GeForce MX150',
  'Windows 10',
  '1.3kg',
  79653.6),
 ('Acer',
  'Ultrabook',
  14.0,
  'IPS Panel Full HD 1920x1080',
  'Intel Core i5 8250U 1.6GHz',
  '8GB',
  '256GB SSD',
  'Intel UHD Graphics 620',
  'Windows 10',
  '1.6kg',
  41025.6),
 ('HP',
  'Notebook',
  15.6,
  '1366x768',
  'Intel Core i5 7200U 2.5GHz',
  '4GB',
  '500GB HDD',
  'Intel HD Graphics 620',
  'No OS',
  '1.86kg',
  20986.992),
 ('HP',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i3 6006U 2GHz',
  '4GB',
  '500GB HDD',
  'Intel HD Graphics 520',
  'No OS',
  '1.86kg',
  18381.0672),
 ('Apple',
  'Ultrabook',
  15.4,
  'IPS Panel Retina Display 2880x1800',
  'Intel Core i7 2.8GHz',
  '16GB',
  '256GB SSD',
  'AMD Radeon Pro 555',
  'macOS',
  '1.83kg',
  130001.6016),
 ('Dell',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i3 6006U 2GHz',
  '4GB',
  '256GB SSD',
  'AMD Radeon R5 M430',
  'Windows 10',
  '2.2kg',
  26581.392),
 ('Apple',
  'Ultrabook',
  12.0,
  'IPS Panel Retina Display 2304x1440',
  'Intel Core M m3 1.2GHz',
  '8GB',
  '256GB SSD',
  'Intel HD Graphics 615',
  'macOS',
  '0.92kg',
  67260.672),
 ('Apple',
  'Ultrabook',
  13.3,
  'IPS Panel Retina Display 2560x1600',
  'Intel Core i5 2.3GHz',
  '8GB',
  '256GB SSD',
  'Intel Iris Plus Graphics 640',
  'macOS',
  '1.37kg',
  80908.344),
 ('Dell',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i7 7500U 2.7GHz',
  '8GB',
  '256GB SSD',
  'AMD Radeon R5 M430',
  'Windows 10',
  '2.2kg',
  39693.6),
 ('Apple',
  'Ultrabook',
  15.4,
  'IPS Panel Retina Display 2880x1800',
  'Intel Core i7 2.9GHz',
  '16GB',
  '512GB SSD',
  'AMD Radeon Pro 560',
  'macOS',
  '1.83kg',
  152274.24),
 ('Lenovo',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i3 7100U 2.4GHz',
  '8GB',
  '1TB HDD',
  'Nvidia GeForce 940MX',
  'No OS',
  '2.2kg',
  26586.72),
 ('Dell',
  'Ultrabook',
  13.3,
  'IPS Panel Full HD / Touchscreen 1920x1080',
  'Intel Core i5 8250U 1.6GHz',
  '8GB',
  '128GB SSD',
  'Intel UHD Graphics 620',
  'Windows 10',
  '1.22kg',
  52161.12),
 ('Asus',
  'Netbook',
  11.6,
  '1366x768',
  'Intel Atom x5-Z8350 1.44GHz',
  '2GB',
  '32GB Flash Storage',
  'Intel HD Graphics 400',
  'Windows 10',
  '0.98kg',
  10224.432),
 ('Lenovo',
  'Gaming',
  15.6,
  'IPS Panel Full HD 1920x1080',
  'Intel Core i5 7300HQ 2.5GHz',
  '8GB',
  '128GB SSD +  1TB HDD',
  'Nvidia GeForce GTX 1050',
  'Windows 10',
  '2.5kg',
  53226.72),
 ('HP',
  'Notebook',
  15.6,
  '1366x768',
  'AMD E-Series E2-9000e 1.5GHz',
  '4GB',
  '500GB HDD',
  'AMD Radeon R2',
  'No OS',
  '1.86kg',
  13746.24),
 ('Dell',
  '2 in 1 Convertible',
  13.3,
  'Full HD / Touchscreen 1920x1080',
  'Intel Core i5 8250U 1.6GHz',
  '8GB',
  '256GB SSD',
  'Intel UHD Graphics 620',
  'Windows 10',
  '1.62kg',
  43636.32),
 ('HP',
  'Ultrabook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i7 8550U 1.8GHz',
  '8GB',
  '256GB SSD',
  'Intel HD Graphics 620',
  'Windows 10',
  '1.91kg',
  35111.52),
 ('Dell',
  'Notebook',
  15.6,
  '1366x768',
  'Intel Core i3 6006U 2GHz',
  '4GB',
  '1TB HDD',
  'Intel HD Graphics 520',
  'Windows 10',
  '2.3kg',
  22305.1392),
 ('Apple',
  'Ultrabook',
  13.3,
  '1440x900',
  'Intel Core i5 1.6GHz',
  '8GB',
  '128GB Flash Storage',
  'Intel HD Graphics 6000',
  'Mac OS X',
  '1.35kg',
  58554.72),
 ('Dell',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i5 8250U 1.6GHz',
  '8GB',
  '256GB SSD',
  'AMD Radeon 530',
  'Windows 10',
  '2.2kg',
  42624.0),
 ('Dell',
  'Ultrabook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i7 8650U 1.9GHz',
  '8GB',
  '256GB SSD +  256GB SSD',
  'Intel UHD Graphics 620',
  'Windows 10',
  '1.88kg',
  69157.44),
 ('HP',
  'Notebook',
  17.3,
  'Full HD 1920x1080',
  'Intel Core i5 8250U 1.6GHz',
  '8GB',
  '1TB HDD',
  'Nvidia GeForce 930MX',
  'Windows 10',
  '2.5kg',
  47738.88),
 ('Chuwi',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Atom x5-Z8300 1.44GHz',
  '4GB',
  '64GB Flash Storage',
  'Intel HD Graphics',
  'Windows 10',
  '1.89kg',
  13053.0672),
 ('Asus',
  'Notebook',
  14.0,
  '1366x768',
  'AMD E-Series E2-6110 1.5GHz',
  '2GB',
  '32GB Flash Storage',
  'AMD Radeon R2',
  'Windows 10',
  '1.65kg',
  10602.72),
 ('HP',
  'Notebook',
  17.3,
  'Full HD 1920x1080',
  'AMD A6-Series 9220 2.5GHz',
  '4GB',
  '500GB HDD',
  'AMD Radeon 530',
  'Windows 10',
  '2.71kg',
  23389.92),
 ('Dell',
  'Ultrabook',
  13.3,
  'Touchscreen / Quad HD+ 3200x1800',
  'Intel Core i7 8550U 1.8GHz',
  '16GB',
  '512GB SSD',
  'Intel UHD Graphics 620',
  'Windows 10',
  '1.2kg',
  99580.32),
 ('Apple',
  'Ultrabook',
  13.3,
  '1440x900',
  'Intel Core i5 1.6GHz',
  '8GB',
  '256GB Flash Storage',
  'Intel HD Graphics 6000',
  'Mac OS X',
  '1.35kg',
  53173.44),
 ('Lenovo',
  'Notebook',
  14.0,
  '1366x768',
  'Intel Celeron Dual Core N3350 1.1GHz',
  '4GB',
  '64GB Flash Storage',
  'Intel HD Graphics 500',
  'Windows 10',
  '1.44kg',
  13266.72),
 ('Acer',
  'Notebook',
  15.6,
  '1366x768',
  'Intel Core i3 7130U 2.7GHz',
  '4GB',
  '1TB HDD',
  'Intel HD Graphics 620',
  'Linux',
  '2.1kg',
  19553.76),
 ('Dell',
  'Notebook',
  17.3,
  'IPS Panel Full HD 1920x1080',
  'Intel Core i5 8250U 1.6GHz',
  '8GB',
  '128GB SSD +  1TB HDD',
  'AMD Radeon 530',
  'Windows 10',
  '2.8kg',
  52161.12),
 ('HP',
  'Notebook',
  15.6,
  '1366x768',
  'Intel Core i5 7200U 2.5GHz',
  '4GB',
  '1TB HDD',
  'Intel HD Graphics 620',
  'Windows 10',
  '1.86kg',
  26037.4032),
 ('HP',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i5 8250U 1.6GHz',
  '8GB',
  '256GB SSD',
  'Nvidia GeForce 930MX ',
  'Windows 10',
  '2.1kg',
  46833.12),
 ('Asus',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i3 6006U 2GHz',
  '4GB',
  '1TB HDD',
  'Intel HD Graphics 620',
  'Linux',
  '2kg',
  20725.92),
 ('Dell',
  'Gaming',
  15.6,
  'IPS Panel Full HD 1920x1080',
  'Intel Core i7 7700HQ 2.8GHz',
  '16GB',
  '256GB SSD +  1TB HDD',
  'Nvidia GeForce GTX 1060',
  'Windows 10',
  '2.65kg',
  79866.72),
 ('Asus',
  'Notebook',
  15.6,
  '1366x768',
  'Intel Core i5 7200U 2.5GHz',
  '8GB',
  '1TB HDD',
  'Nvidia GeForce 940MX',
  'Linux',
  '2.3kg',
  27864.9072),
 ('Acer',
  'Notebook',
  15.6,
  'IPS Panel Full HD 1920x1080',
  'Intel Core i5 8250U 1.6GHz',
  '4GB',
  '256GB SSD',
  'Intel UHD Graphics 620',
  'Windows 10',
  '2.2kg',
  36336.96),
 ('Dell',
  '2 in 1 Convertible',
  17.3,
  'Full HD / Touchscreen 1920x1080',
  'Intel Core i5 8250U 1.6GHz',
  '12GB',
  '1TB HDD',
  'Nvidia GeForce 150MX',
  'Windows 10',
  '2.77kg',
  53226.72),
 ('Apple',
  'Ultrabook',
  13.3,
  'IPS Panel Retina Display 2560x1600',
  'Intel Core i5 2.0GHz',
  '8GB',
  '256GB SSD',
  'Intel Iris Graphics 540',
  'macOS',
  '1.37kg',
  75604.32),
 ('Lenovo',
  'Notebook',
  15.6,
  '1366x768',
  'Intel Core i3 6006U 2GHz',
  '4GB',
  '128GB SSD',
  'Intel HD Graphics 520',
  'No OS',
  '2.2kg',
  19660.32),
 ('Asus',
  'Gaming',
  17.3,
  'Full HD 1920x1080',
  'AMD Ryzen 1700 3GHz',
  '8GB',
  '256GB SSD +  1TB HDD',
  'AMD Radeon RX 580',
  'Windows 10',
  '3.2kg',
  69210.72),
 ('Dell',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i5 7200U 2.5GHz',
  '4GB',
  '256GB SSD',
  'AMD Radeon R5 M430',
  'Windows 10',
  '2.3kg',
  34045.92),
 ('Asus',
  'Notebook',
  17.3,
  '1366x768',
  'Intel Pentium Quad Core N4200 1.1GHz',
  '4GB',
  '1TB HDD',
  'Nvidia GeForce 920MX',
  'Windows 10',
  '2.8kg',
  24828.48),
 ('Lenovo',
  '2 in 1 Convertible',
  10.1,
  'IPS Panel Touchscreen 1920x1200',
  'Intel Atom x5-Z8550 1.44GHz',
  '4GB',
  '64GB Flash Storage',
  'Intel HD Graphics 400',
  'Android',
  '0.69kg',
  16996.32),
 ('Acer',
  'Notebook',
  15.6,
  'IPS Panel Full HD 1920x1080',
  'Intel Core i7 8550U 1.8GHz',
  '8GB',
  '256GB SSD',
  'Nvidia GeForce MX150',
  'Windows 10',
  '2.2kg',
  44808.48),
 ('HP',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'AMD A6-Series 9220 2.5GHz',
  '4GB',
  '256GB SSD',
  'AMD Radeon R4 Graphics',
  'Windows 10',
  '1.86kg',
  21231.5472),
 ('HP',
  'Notebook',
  13.3,
  'Full HD 1920x1080',
  'Intel Core i7 8550U 1.8GHz',
  '8GB',
  '512GB SSD',
  'Intel UHD Graphics 620',
  'Windows 10',
  '1.49kg',
  58767.84),
 ('Acer',
  'Notebook',
  15.6,
  '1366x768',
  'Intel Core i3 7100U 2.4GHz',
  '4GB',
  '1TB HDD',
  'Intel HD Graphics 620',
  'Windows 10',
  '2.4kg',
  20459.52),
 ('Dell',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i7 8550U 1.8GHz',
  '8GB',
  '256GB SSD',
  'AMD Radeon 520',
  'Windows 10',
  '2.13kg',
  40908.384),
 ('HP',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i3 6006U 2GHz',
  '4GB',
  '128GB SSD',
  'Intel HD Graphics 520',
  'Windows 10',
  '1.91kg',
  23389.92),
 ('Asus',
  'Notebook',
  15.6,
  '1366x768',
  'Intel Core i5 7200U 2.5GHz',
  '4GB',
  '256GB SSD',
  'Intel HD Graphics 620',
  'Windows 10',
  '2kg',
  31232.2032),
 ('MSI',
  'Gaming',
  17.3,
  'Full HD 1920x1080',
  'Intel Core i7 7700HQ 2.8GHz',
  '16GB',
  '256GB SSD +  2TB HDD',
  'Nvidia GeForce GTX 1070',
  'Windows 10',
  '2.43kg',
  130482.72),
 ('Asus',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i3 6006U 2GHz',
  '4GB',
  '256GB SSD',
  'Intel HD Graphics 520',
  'Linux',
  '2kg',
  22111.2),
 ('Dell',
  'Notebook',
  17.3,
  'Full HD 1920x1080',
  'Intel Core i7 8550U 1.8GHz',
  '16GB',
  '256GB SSD +  2TB HDD',
  'AMD Radeon 530',
  'Windows 10',
  '2.8kg',
  69210.72),
 ('Dell',
  'Ultrabook',
  14.0,
  'Full HD 1920x1080',
  'Intel Core i5 8250U 1.6GHz',
  '8GB',
  '256GB SSD',
  'Intel UHD Graphics 620',
  'Windows 10',
  '1.7kg',
  46833.12),
 ('Lenovo',
  'Notebook',
  14.0,
  'IPS Panel Full HD 1920x1080',
  'Intel Core i3 7130U 2.7GHz',
  '8GB',
  '256GB SSD',
  'Intel HD Graphics 620',
  'No OS',
  '1.7kg',
  31914.72),
 ('Asus',
  'Notebook',
  14.0,
  'Full HD 1920x1080',
  'Intel Core i5 8250U 1.6GHz',
  '8GB',
  '256GB SSD',
  'Intel UHD Graphics 620',
  'Windows 10',
  '1.4kg',
  50136.48),
 ('HP',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i5 7200U 2.5GHz',
  '8GB',
  '256GB SSD',
  'Intel HD Graphics 620',
  'Windows 10',
  '1.86kg',
  36763.2),
 ('Asus',
  'Ultrabook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i7 7700HQ 2.8GHz',
  '16GB',
  '512GB SSD',
  'Nvidia GeForce GTX 1050 Ti',
  'Windows 10',
  '1.8kg',
  105654.24),
 ('HP',
  'Notebook',
  15.6,
  '1366x768',
  'Intel Core i3 6006U 2GHz',
  '4GB',
  '500GB HDD',
  'AMD Radeon 520',
  'Windows 10',
  '1.86kg',
  23373.4032),
 ('HP',
  'Notebook',
  14.0,
  '1366x768',
  'Intel Celeron Dual Core N3060 1.6GHz',
  '4GB',
  '32GB SSD',
  'Intel HD Graphics 400',
  'Windows 10',
  '1.44kg',
  12201.12),
 ('Lenovo',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i5 7200U 2.5GHz',
  '4GB',
  '1TB HDD',
  'Intel HD Graphics 620',
  'Windows 10',
  '1.9kg',
  29250.72),
 ('Asus',
  'Gaming',
  17.3,
  'Full HD 1920x1080',
  'Intel Core i7 7700HQ 2.8GHz',
  '12GB',
  '1TB HDD',
  'Nvidia GeForce GTX 1050 Ti',
  'Linux',
  '3kg',
  50562.72),
 ('Microsoft',
  'Ultrabook',
  13.5,
  'Touchscreen 2256x1504',
  'Intel Core i5 7200U 2.5GHz',
  '4GB',
  '128GB SSD',
  'Intel HD Graphics 620',
  'Windows 10 S',
  '1.252kg',
  58021.92),
 ('Dell',
  'Ultrabook',
  13.3,
  'IPS Panel Full HD 1920x1080',
  'Intel Core i7 8550U 1.8GHz',
  '8GB',
  '256GB SSD',
  'AMD Radeon 530',
  'Windows 10',
  '1.4kg',
  50882.4),
 ('Dell',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i7 8550U 1.8GHz',
  '8GB',
  '256GB SSD',
  'AMD Radeon 530',
  'Windows 10',
  '2.2kg',
  46353.6),
 ('MSI',
  'Gaming',
  17.3,
  'Full HD 1920x1080',
  'Intel Core i5 7300HQ 2.5GHz',
  '8GB',
  '128GB SSD +  1TB HDD',
  'Nvidia GeForce GTX 1050',
  'Windows 10',
  '2.7kg',
  58341.6),
 ('Acer',
  'Notebook',
  14.0,
  '1366x768',
  'Intel Core i3 6006U 2GHz',
  '8GB',
  '1TB HDD',
  'Intel HD Graphics 520',
  'Windows 10',
  '2.1kg',
  20725.92),
 ('Asus',
  'Gaming',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i7 7700HQ 2.8GHz',
  '8GB',
  '1TB HDD',
  'Nvidia GeForce GTX 1050',
  'Windows 10',
  '2.2kg',
  50562.72),
 ('Lenovo',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i5 7200U 2.5GHz',
  '8GB',
  '2TB HDD',
  'Intel HD Graphics 620',
  'No OS',
  '2.2kg',
  27652.32),
 ('Dell',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i7 8550U 1.8GHz',
  '8GB',
  '128GB SSD +  1TB HDD',
  'Intel UHD Graphics 620',
  'Windows 10',
  '2.02kg',
  45554.4),
 ('Acer',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i3 7130U 2.7GHz',
  '4GB',
  '1TB HDD',
  'Nvidia GeForce MX130',
  'Windows 10',
  '2.2kg',
  28238.4),
 ('HP',
  'Notebook',
  17.3,
  'Full HD 1920x1080',
  'Intel Core i5 8250U 1.6GHz',
  '8GB',
  '128GB SSD +  1TB HDD',
  'Nvidia GeForce 930MX',
  'Windows 10',
  '2.5kg',
  52054.56),
 ('Dell',
  'Ultrabook',
  15.6,
  'IPS Panel Full HD 1920x1080',
  'Intel Core i5 8250U 1.6GHz',
  '8GB',
  '256GB SSD',
  'Intel UHD Graphics 620',
  'Windows 10',
  '1.88kg',
  58403.4048),
 ('Apple',
  'Ultrabook',
  12.0,
  'IPS Panel Retina Display 2304x1440',
  'Intel Core i5 1.3GHz',
  '8GB',
  '512GB SSD',
  'Intel HD Graphics 615',
  'macOS',
  '0.92kg',
  80452.8),
 ('HP',
  'Notebook',
  14.0,
  'Full HD 1920x1080',
  'Intel Core i5 8250U 1.6GHz',
  '8GB',
  '256GB SSD',
  'Intel HD Graphics 620',
  'Windows 10',
  '1.63kg',
  45820.8),
 ('Lenovo',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'AMD A6-Series 9220 2.5GHz',
  '4GB',
  '128GB SSD',
  'AMD R4 Graphics',
  'Windows 10',
  '2.2kg',
  21258.72),
 ('Acer',
  'Notebook',
  15.6,
  '1366x768',
  'AMD A9-Series 9420 3GHz',
  '4GB',
  '1TB HDD',
  'AMD Radeon R5',
  'Windows 10',
  '2.1kg',
  21045.6),
 ('Dell',
  'Gaming',
  15.6,
  'IPS Panel Full HD 1920x1080',
  'Intel Core i7 7700HQ 2.8GHz',
  '16GB',
  '128GB SSD +  1TB HDD',
  'Nvidia GeForce GTX 1050 Ti',
  'Windows 10',
  '2.65kg',
  71874.72),
 ('HP',
  'Ultrabook',
  15.6,
  'IPS Panel Full HD 1920x1080',
  'Intel Core i7 8550U 1.8GHz',
  '8GB',
  '256GB SSD',
  'Nvidia GeForce GTX 940MX',
  'Windows 10',
  '1.83kg',
  37242.72),
 ('HP',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i5 7200U 2.5GHz',
  '8GB',
  '256GB SSD',
  'Intel HD Graphics 620',
  'Windows 10',
  '1.96kg',
  31914.1872),
 ('Asus',
  'Gaming',
  15.6,
  'IPS Panel Full HD 1920x1080',
  'Intel Core i7 7700HQ 2.8GHz',
  '16GB',
  '128GB SSD +  1TB HDD',
  'Nvidia GeForce GTX 1060',
  'Windows 10',
  '2.2kg',
  77202.72),
 ('Dell',
  'Ultrabook',
  13.3,
  'IPS Panel Full HD 1920x1080',
  'Intel Core i7 8550U 1.8GHz',
  '8GB',
  '256GB SSD',
  'Intel UHD Graphics 620',
  'Windows 10',
  '1.21kg',
  87858.72),
 ('Asus',
  'Gaming',
  15.6,
  'Full HD 1920x1080',
  'AMD FX 9830P 3GHz',
  '8GB',
  '1TB HDD',
  'AMD Radeon RX 560',
  'Windows 10',
  '2.45kg',
  37242.72),
 ('Acer',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i7 8550U 1.8GHz',
  '8GB',
  '1TB HDD',
  'Nvidia GeForce MX150',
  'Windows 10',
  '2.2kg',
  36709.92),
 ('HP',
  'Notebook',
  13.3,
  'Full HD 1920x1080',
  'Intel Core i7 8550U 1.8GHz',
  '16GB',
  '512GB SSD',
  'Intel UHD Graphics 620',
  'Windows 10',
  '1.49kg',
  63776.16),
 ('Dell',
  'Gaming',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i5 7300HQ 2.5GHz',
  '8GB',
  '256GB SSD',
  'Nvidia GeForce GTX 1060',
  'Windows 10',
  '2.65kg',
  63669.6),
 ('Asus',
  'Ultrabook',
  14.0,
  'Full HD 1920x1080',
  'Intel Core i7 7500U 2.7GHz',
  '8GB',
  '256GB SSD',
  'Intel HD Graphics 620',
  'Windows 10',
  '1.25kg',
  55890.72),
 ('Acer',
  '2 in 1 Convertible',
  13.3,
  'IPS Panel Full HD / Touchscreen 1920x1080',
  'Intel Core i5 8250U 1.6GHz',
  '8GB',
  '256GB SSD',
  'Intel UHD Graphics 620',
  'Windows 10',
  '1.5kg',
  45128.16),
 ('Dell',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i7 7500U 2.7GHz',
  '8GB',
  '1TB HDD',
  'AMD Radeon R5 M430',
  'Linux',
  '2.2kg',
  31962.672),
 ('Dell',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i3 6006U 2GHz',
  '4GB',
  '256GB SSD',
  'AMD Radeon R5 M430',
  'Linux',
  '2.2kg',
  25840.8),
 ('Asus',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i3 7100U 2.4GHz',
  '6GB',
  '256GB SSD',
  'Nvidia GeForce 920M',
  'Windows 10',
  '2kg',
  30742.56),
 ('HP',
  'Gaming',
  15.6,
  'IPS Panel Full HD 1920x1080',
  'Intel Core i7 7700HQ 2.8GHz',
  '12GB',
  '128GB SSD +  1TB HDD',
  'Nvidia GeForce GTX 1050',
  'Windows 10',
  '2.62kg',
  66546.72),
 ('HP',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i7 7500U 2.7GHz',
  '8GB',
  '256GB SSD',
  'AMD Radeon 530',
  'Windows 10',
  '1.91kg',
  38308.32),
 ('HP',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'AMD E-Series E2-9000e 1.5GHz',
  '4GB',
  '500GB HDD',
  'AMD Radeon R2',
  'Windows 10',
  '2.1kg',
  18594.72),
 ('Dell',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i5 8250U 1.6GHz',
  '8GB',
  '1TB HDD',
  'AMD Radeon 520',
  'Linux',
  '2.2kg',
  34472.16),
 ('HP',
  'Ultrabook',
  13.3,
  'IPS Panel Full HD 1920x1080',
  'Intel Core i7 7500U 2.7GHz',
  '8GB',
  '256GB SSD',
  'Nvidia GeForce MX150',
  'Windows 10',
  '1.38kg',
  59620.32),
 ('Microsoft',
  'Ultrabook',
  13.5,
  'Touchscreen 2256x1504',
  'Intel Core i5 7200U 2.5GHz',
  '8GB',
  '256GB SSD',
  'Intel HD Graphics 620',
  'Windows 10 S',
  '1.252kg',
  71395.2),
 ('HP',
  'Notebook',
  14.0,
  'IPS Panel Full HD 1920x1080',
  'Intel Core i5 7200U 2.5GHz',
  '6GB',
  '256GB SSD',
  'Nvidia GeForce 940MX',
  'Windows 10',
  '1.58kg',
  35111.52),
 ('Lenovo',
  'Notebook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i3 6006U 2GHz',
  '4GB',
  '1TB HDD',
  'Intel HD Graphics 520',
  'Windows 10',
  '1.85kg',
  22105.872),
 ('Asus',
  'Ultrabook',
  14.0,
  'IPS Panel Full HD 1920x1080',
  'Intel Core i7 7500U 2.7GHz',
  '8GB',
  '256GB SSD',
  'Nvidia GeForce 940MX',
  'Windows 10',
  '1.3kg',
  63563.04),
 ('MSI',
  'Gaming',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i7 7700HQ 2.8GHz',
  '16GB',
  '256GB SSD +  1TB HDD',
  'Nvidia GeForce GTX 1050 Ti',
  'Windows 10',
  '2.2kg',
  69210.72),
 ('Lenovo',
  'Notebook',
  14.0,
  'IPS Panel Full HD 1920x1080',
  'Intel Core i7 7500U 2.7GHz',
  '8GB',
  '256GB SSD',
  'Intel HD Graphics 620',
  'Windows 10',
  '1.58kg',
  78854.4),
 ('Asus',
  'Ultrabook',
  15.6,
  'Full HD 1920x1080',
  'Intel Core i7 8550U 1.8GHz',
  '16GB',

In [ ]:
cursor.executemany(insert_query, data_tuples)
mydb.commit()

In [ ]:
cursor.execute("select * from laptops")

for i in cursor:
    print(i)

('Apple', 'Ultrabook', 13.3, 'IPS Panel Retina Display 2560x1600', 'Intel Core i5 2.3GHz', '8GB', '128GB SSD', 'Intel Iris Plus Graphics 640', 'macOS', '1.37kg', 71378.7)
('Apple', 'Ultrabook', 13.3, '1440x900', 'Intel Core i5 1.8GHz', '8GB', '128GB Flash Storage', 'Intel HD Graphics 6000', 'macOS', '1.34kg', 47895.5)
('HP', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i5 7200U 2.5GHz', '8GB', '256GB SSD', 'Intel HD Graphics 620', 'No OS', '1.86kg', 30636.0)
('Apple', 'Ultrabook', 15.4, 'IPS Panel Retina Display 2880x1800', 'Intel Core i7 2.7GHz', '16GB', '512GB SSD', 'AMD Radeon Pro 455', 'macOS', '1.83kg', 135195.0)
('Apple', 'Ultrabook', 13.3, 'IPS Panel Retina Display 2560x1600', 'Intel Core i5 3.1GHz', '8GB', '256GB SSD', 'Intel Iris Plus Graphics 650', 'macOS', '1.37kg', 96095.8)
('Acer', 'Notebook', 15.6, '1366x768', 'AMD A9-Series 9420 3GHz', '4GB', '500GB HDD', 'AMD Radeon R5', 'Windows 10', '2.1kg', 21312.0)
('Apple', 'Ultrabook', 15.4, 'IPS Panel Retina Display 2880x1800', 'Intel Core i7 2.2GHz', '16GB', '256GB Flash Storage', 'Intel Iris Pro Graphics', 'Mac OS X', '2.04kg', 114018.0)
('Apple', 'Ultrabook', 13.3, '1440x900', 'Intel Core i5 1.8GHz', '8GB', '256GB Flash Storage', 'Intel HD Graphics 6000', 'macOS', '1.34kg', 61735.5)
('Asus', 'Ultrabook', 14.0, 'Full HD 1920x1080', 'Intel Core i7 8550U 1.8GHz', '16GB', '512GB SSD', 'Nvidia GeForce MX150', 'Windows 10', '1.3kg', 79653.6)
('Acer', 'Ultrabook', 14.0, 'IPS Panel Full HD 1920x1080', 'Intel Core i5 8250U 1.6GHz', '8GB', '256GB SSD', 'Intel UHD Graphics 620', 'Windows 10', '1.6kg', 41025.6)
('HP', 'Notebook', 15.6, '1366x768', 'Intel Core i5 7200U 2.5GHz', '4GB', '500GB HDD', 'Intel HD Graphics 620', 'No OS', '1.86kg', 20987.0)
('HP', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i3 6006U 2GHz', '4GB', '500GB HDD', 'Intel HD Graphics 520', 'No OS', '1.86kg', 18381.1)
('Apple', 'Ultrabook', 15.4, 'IPS Panel Retina Display 2880x1800', 'Intel Core i7 2.8GHz', '16GB', '256GB SSD', 'AMD Radeon Pro 555', 'macOS', '1.83kg', 130002.0)
('Dell', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i3 6006U 2GHz', '4GB', '256GB SSD', 'AMD Radeon R5 M430', 'Windows 10', '2.2kg', 26581.4)
('Apple', 'Ultrabook', 12.0, 'IPS Panel Retina Display 2304x1440', 'Intel Core M m3 1.2GHz', '8GB', '256GB SSD', 'Intel HD Graphics 615', 'macOS', '0.92kg', 67260.7)
('Apple', 'Ultrabook', 13.3, 'IPS Panel Retina Display 2560x1600', 'Intel Core i5 2.3GHz', '8GB', '256GB SSD', 'Intel Iris Plus Graphics 640', 'macOS', '1.37kg', 80908.3)
('Dell', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i7 7500U 2.7GHz', '8GB', '256GB SSD', 'AMD Radeon R5 M430', 'Windows 10', '2.2kg', 39693.6)
('Apple', 'Ultrabook', 15.4, 'IPS Panel Retina Display 2880x1800', 'Intel Core i7 2.9GHz', '16GB', '512GB SSD', 'AMD Radeon Pro 560', 'macOS', '1.83kg', 152274.0)
('Lenovo', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i3 7100U 2.4GHz', '8GB', '1TB HDD', 'Nvidia GeForce 940MX', 'No OS', '2.2kg', 26586.7)
('Dell', 'Ultrabook', 13.3, 'IPS Panel Full HD / Touchscreen 1920x1080', 'Intel Core i5 8250U 1.6GHz', '8GB', '128GB SSD', 'Intel UHD Graphics 620', 'Windows 10', '1.22kg', 52161.1)
('Asus', 'Netbook', 11.6, '1366x768', 'Intel Atom x5-Z8350 1.44GHz', '2GB', '32GB Flash Storage', 'Intel HD Graphics 400', 'Windows 10', '0.98kg', 10224.4)
('Lenovo', 'Gaming', 15.6, 'IPS Panel Full HD 1920x1080', 'Intel Core i5 7300HQ 2.5GHz', '8GB', '128GB SSD +  1TB HDD', 'Nvidia GeForce GTX 1050', 'Windows 10', '2.5kg', 53226.7)
('HP', 'Notebook', 15.6, '1366x768', 'AMD E-Series E2-9000e 1.5GHz', '4GB', '500GB HDD', 'AMD Radeon R2', 'No OS', '1.86kg', 13746.2)
('Dell', '2 in 1 Convertible', 13.3, 'Full HD / Touchscreen 1920x1080', 'Intel Core i5 8250U 1.6GHz', '8GB', '256GB SSD', 'Intel UHD Graphics 620', 'Windows 10', '1.62kg', 43636.3)
('HP', 'Ultrabook', 15.6, 'Full HD 1920x1080', 'Intel Core i7 8550U 1.8GHz', '8GB', '256GB SSD', 'Intel HD Graphics 620', 'Windows 10', '1.91kg', 35111.5)
('Dell', 'Notebook', 15.6, '1366x768', 'Intel Core i3 6006U 2GHz', '4GB', '1TB HDD', 'Intel HD Graphics 520', 'Windows 10', '2.3kg', 22305.1)
('Apple', 'Ultrabook', 13.3, '1440x900', 'Intel Core i5 1.6GHz', '8GB', '128GB Flash Storage', 'Intel HD Graphics 6000', 'Mac OS X', '1.35kg', 58554.7)
('Dell', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i5 8250U 1.6GHz', '8GB', '256GB SSD', 'AMD Radeon 530', 'Windows 10', '2.2kg', 42624.0)
('Dell', 'Ultrabook', 15.6, 'Full HD 1920x1080', 'Intel Core i7 8650U 1.9GHz', '8GB', '256GB SSD +  256GB SSD', 'Intel UHD Graphics 620', 'Windows 10', '1.88kg', 69157.4)
('HP', 'Notebook', 17.3, 'Full HD 1920x1080', 'Intel Core i5 8250U 1.6GHz', '8GB', '1TB HDD', 'Nvidia GeForce 930MX', 'Windows 10', '2.5kg', 47738.9)
('Chuwi', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Atom x5-Z8300 1.44GHz', '4GB', '64GB Flash Storage', 'Intel HD Graphics', 'Windows 10', '1.89kg', 13053.1)
('Asus', 'Notebook', 14.0, '1366x768', 'AMD E-Series E2-6110 1.5GHz', '2GB', '32GB Flash Storage', 'AMD Radeon R2', 'Windows 10', '1.65kg', 10602.7)
('HP', 'Notebook', 17.3, 'Full HD 1920x1080', 'AMD A6-Series 9220 2.5GHz', '4GB', '500GB HDD', 'AMD Radeon 530', 'Windows 10', '2.71kg', 23389.9)
('Dell', 'Ultrabook', 13.3, 'Touchscreen / Quad HD+ 3200x1800', 'Intel Core i7 8550U 1.8GHz', '16GB', '512GB SSD', 'Intel UHD Graphics 620', 'Windows 10', '1.2kg', 99580.3)
('Apple', 'Ultrabook', 13.3, '1440x900', 'Intel Core i5 1.6GHz', '8GB', '256GB Flash Storage', 'Intel HD Graphics 6000', 'Mac OS X', '1.35kg', 53173.4)
('Lenovo', 'Notebook', 14.0, '1366x768', 'Intel Celeron Dual Core N3350 1.1GHz', '4GB', '64GB Flash Storage', 'Intel HD Graphics 500', 'Windows 10', '1.44kg', 13266.7)
('Acer', 'Notebook', 15.6, '1366x768', 'Intel Core i3 7130U 2.7GHz', '4GB', '1TB HDD', 'Intel HD Graphics 620', 'Linux', '2.1kg', 19553.8)
('Dell', 'Notebook', 17.3, 'IPS Panel Full HD 1920x1080', 'Intel Core i5 8250U 1.6GHz', '8GB', '128GB SSD +  1TB HDD', 'AMD Radeon 530', 'Windows 10', '2.8kg', 52161.1)
('HP', 'Notebook', 15.6, '1366x768', 'Intel Core i5 7200U 2.5GHz', '4GB', '1TB HDD', 'Intel HD Graphics 620', 'Windows 10', '1.86kg', 26037.4)
('HP', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i5 8250U 1.6GHz', '8GB', '256GB SSD', 'Nvidia GeForce 930MX ', 'Windows 10', '2.1kg', 46833.1)
('Asus', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i3 6006U 2GHz', '4GB', '1TB HDD', 'Intel HD Graphics 620', 'Linux', '2kg', 20725.9)
('Dell', 'Gaming', 15.6, 'IPS Panel Full HD 1920x1080', 'Intel Core i7 7700HQ 2.8GHz', '16GB', '256GB SSD +  1TB HDD', 'Nvidia GeForce GTX 1060', 'Windows 10', '2.65kg', 79866.7)
('Asus', 'Notebook', 15.6, '1366x768', 'Intel Core i5 7200U 2.5GHz', '8GB', '1TB HDD', 'Nvidia GeForce 940MX', 'Linux', '2.3kg', 27864.9)
('Acer', 'Notebook', 15.6, 'IPS Panel Full HD 1920x1080', 'Intel Core i5 8250U 1.6GHz', '4GB', '256GB SSD', 'Intel UHD Graphics 620', 'Windows 10', '2.2kg', 36337.0)
('Dell', '2 in 1 Convertible', 17.3, 'Full HD / Touchscreen 1920x1080', 'Intel Core i5 8250U 1.6GHz', '12GB', '1TB HDD', 'Nvidia GeForce 150MX', 'Windows 10', '2.77kg', 53226.7)
('Apple', 'Ultrabook', 13.3, 'IPS Panel Retina Display 2560x1600', 'Intel Core i5 2.0GHz', '8GB', '256GB SSD', 'Intel Iris Graphics 540', 'macOS', '1.37kg', 75604.3)
('Lenovo', 'Notebook', 15.6, '1366x768', 'Intel Core i3 6006U 2GHz', '4GB', '128GB SSD', 'Intel HD Graphics 520', 'No OS', '2.2kg', 19660.3)
('Asus', 'Gaming', 17.3, 'Full HD 1920x1080', 'AMD Ryzen 1700 3GHz', '8GB', '256GB SSD +  1TB HDD', 'AMD Radeon RX 580', 'Windows 10', '3.2kg', 69210.7)
('Dell', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i5 7200U 2.5GHz', '4GB', '256GB SSD', 'AMD Radeon R5 M430', 'Windows 10', '2.3kg', 34045.9)
('Asus', 'Notebook', 17.3, '1366x768', 'Intel Pentium Quad Core N4200 1.1GHz', '4GB', '1TB HDD', 'Nvidia GeForce 920MX', 'Windows 10', '2.8kg', 24828.5)
('Lenovo', '2 in 1 Convertible', 10.1, 'IPS Panel Touchscreen 1920x1200', 'Intel Atom x5-Z8550 1.44GHz', '4GB', '64GB Flash Storage', 'Intel HD Graphics 400', 'Android', '0.69kg', 16996.3)
('Acer', 'Notebook', 15.6, 'IPS Panel Full HD 1920x1080', 'Intel Core i7 8550U 1.8GHz', '8GB', '256GB SSD', 'Nvidia GeForce MX150', 'Windows 10', '2.2kg', 44808.5)
('HP', 'Notebook', 15.6, 'Full HD 1920x1080', 'AMD A6-Series 9220 2.5GHz', '4GB', '256GB SSD', 'AMD Radeon R4 Graphics', 'Windows 10', '1.86kg', 21231.5)
('HP', 'Notebook', 13.3, 'Full HD 1920x1080', 'Intel Core i7 8550U 1.8GHz', '8GB', '512GB SSD', 'Intel UHD Graphics 620', 'Windows 10', '1.49kg', 58767.8)
('Acer', 'Notebook', 15.6, '1366x768', 'Intel Core i3 7100U 2.4GHz', '4GB', '1TB HDD', 'Intel HD Graphics 620', 'Windows 10', '2.4kg', 20459.5)
('Dell', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i7 8550U 1.8GHz', '8GB', '256GB SSD', 'AMD Radeon 520', 'Windows 10', '2.13kg', 40908.4)
('HP', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i3 6006U 2GHz', '4GB', '128GB SSD', 'Intel HD Graphics 520', 'Windows 10', '1.91kg', 23389.9)
('Asus', 'Notebook', 15.6, '1366x768', 'Intel Core i5 7200U 2.5GHz', '4GB', '256GB SSD', 'Intel HD Graphics 620', 'Windows 10', '2kg', 31232.2)
('MSI', 'Gaming', 17.3, 'Full HD 1920x1080', 'Intel Core i7 7700HQ 2.8GHz', '16GB', '256GB SSD +  2TB HDD', 'Nvidia GeForce GTX 1070', 'Windows 10', '2.43kg', 130483.0)
('Asus', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i3 6006U 2GHz', '4GB', '256GB SSD', 'Intel HD Graphics 520', 'Linux', '2kg', 22111.2)
('Dell', 'Notebook', 17.3, 'Full HD 1920x1080', 'Intel Core i7 8550U 1.8GHz', '16GB', '256GB SSD +  2TB HDD', 'AMD Radeon 530', 'Windows 10', '2.8kg', 69210.7)
('Dell', 'Ultrabook', 14.0, 'Full HD 1920x1080', 'Intel Core i5 8250U 1.6GHz', '8GB', '256GB SSD', 'Intel UHD Graphics 620', 'Windows 10', '1.7kg', 46833.1)
('Lenovo', 'Notebook', 14.0, 'IPS Panel Full HD 1920x1080', 'Intel Core i3 7130U 2.7GHz', '8GB', '256GB SSD', 'Intel HD Graphics 620', 'No OS', '1.7kg', 31914.7)
('Asus', 'Notebook', 14.0, 'Full HD 1920x1080', 'Intel Core i5 8250U 1.6GHz', '8GB', '256GB SSD', 'Intel UHD Graphics 620', 'Windows 10', '1.4kg', 50136.5)
('HP', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i5 7200U 2.5GHz', '8GB', '256GB SSD', 'Intel HD Graphics 620', 'Windows 10', '1.86kg', 36763.2)
('Asus', 'Ultrabook', 15.6, 'Full HD 1920x1080', 'Intel Core i7 7700HQ 2.8GHz', '16GB', '512GB SSD', 'Nvidia GeForce GTX 1050 Ti', 'Windows 10', '1.8kg', 105654.0)
('HP', 'Notebook', 15.6, '1366x768', 'Intel Core i3 6006U 2GHz', '4GB', '500GB HDD', 'AMD Radeon 520', 'Windows 10', '1.86kg', 23373.4)
('HP', 'Notebook', 14.0, '1366x768', 'Intel Celeron Dual Core N3060 1.6GHz', '4GB', '32GB SSD', 'Intel HD Graphics 400', 'Windows 10', '1.44kg', 12201.1)
('Lenovo', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i5 7200U 2.5GHz', '4GB', '1TB HDD', 'Intel HD Graphics 620', 'Windows 10', '1.9kg', 29250.7)
('Asus', 'Gaming', 17.3, 'Full HD 1920x1080', 'Intel Core i7 7700HQ 2.8GHz', '12GB', '1TB HDD', 'Nvidia GeForce GTX 1050 Ti', 'Linux', '3kg', 50562.7)
('Microsoft', 'Ultrabook', 13.5, 'Touchscreen 2256x1504', 'Intel Core i5 7200U 2.5GHz', '4GB', '128GB SSD', 'Intel HD Graphics 620', 'Windows 10 S', '1.252kg', 58021.9)
('Dell', 'Ultrabook', 13.3, 'IPS Panel Full HD 1920x1080', 'Intel Core i7 8550U 1.8GHz', '8GB', '256GB SSD', 'AMD Radeon 530', 'Windows 10', '1.4kg', 50882.4)
('Dell', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i7 8550U 1.8GHz', '8GB', '256GB SSD', 'AMD Radeon 530', 'Windows 10', '2.2kg', 46353.6)
('MSI', 'Gaming', 17.3, 'Full HD 1920x1080', 'Intel Core i5 7300HQ 2.5GHz', '8GB', '128GB SSD +  1TB HDD', 'Nvidia GeForce GTX 1050', 'Windows 10', '2.7kg', 58341.6)
('Acer', 'Notebook', 14.0, '1366x768', 'Intel Core i3 6006U 2GHz', '8GB', '1TB HDD', 'Intel HD Graphics 520', 'Windows 10', '2.1kg', 20725.9)
('Asus', 'Gaming', 15.6, 'Full HD 1920x1080', 'Intel Core i7 7700HQ 2.8GHz', '8GB', '1TB HDD', 'Nvidia GeForce GTX 1050', 'Windows 10', '2.2kg', 50562.7)
('Lenovo', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i5 7200U 2.5GHz', '8GB', '2TB HDD', 'Intel HD Graphics 620', 'No OS', '2.2kg', 27652.3)
('Dell', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i7 8550U 1.8GHz', '8GB', '128GB SSD +  1TB HDD', 'Intel UHD Graphics 620', 'Windows 10', '2.02kg', 45554.4)
('Acer', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i3 7130U 2.7GHz', '4GB', '1TB HDD', 'Nvidia GeForce MX130', 'Windows 10', '2.2kg', 28238.4)
('HP', 'Notebook', 17.3, 'Full HD 1920x1080', 'Intel Core i5 8250U 1.6GHz', '8GB', '128GB SSD +  1TB HDD', 'Nvidia GeForce 930MX', 'Windows 10', '2.5kg', 52054.6)
('Dell', 'Ultrabook', 15.6, 'IPS Panel Full HD 1920x1080', 'Intel Core i5 8250U 1.6GHz', '8GB', '256GB SSD', 'Intel UHD Graphics 620', 'Windows 10', '1.88kg', 58403.4)
('Apple', 'Ultrabook', 12.0, 'IPS Panel Retina Display 2304x1440', 'Intel Core i5 1.3GHz', '8GB', '512GB SSD', 'Intel HD Graphics 615', 'macOS', '0.92kg', 80452.8)
('HP', 'Notebook', 14.0, 'Full HD 1920x1080', 'Intel Core i5 8250U 1.6GHz', '8GB', '256GB SSD', 'Intel HD Graphics 620', 'Windows 10', '1.63kg', 45820.8)
('Lenovo', 'Notebook', 15.6, 'Full HD 1920x1080', 'AMD A6-Series 9220 2.5GHz', '4GB', '128GB SSD', 'AMD R4 Graphics', 'Windows 10', '2.2kg', 21258.7)
('Acer', 'Notebook', 15.6, '1366x768', 'AMD A9-Series 9420 3GHz', '4GB', '1TB HDD', 'AMD Radeon R5', 'Windows 10', '2.1kg', 21045.6)
('Dell', 'Gaming', 15.6, 'IPS Panel Full HD 1920x1080', 'Intel Core i7 7700HQ 2.8GHz', '16GB', '128GB SSD +  1TB HDD', 'Nvidia GeForce GTX 1050 Ti', 'Windows 10', '2.65kg', 71874.7)
('HP', 'Ultrabook', 15.6, 'IPS Panel Full HD 1920x1080', 'Intel Core i7 8550U 1.8GHz', '8GB', '256GB SSD', 'Nvidia GeForce GTX 940MX', 'Windows 10', '1.83kg', 37242.7)
('HP', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i5 7200U 2.5GHz', '8GB', '256GB SSD', 'Intel HD Graphics 620', 'Windows 10', '1.96kg', 31914.2)
('Asus', 'Gaming', 15.6, 'IPS Panel Full HD 1920x1080', 'Intel Core i7 7700HQ 2.8GHz', '16GB', '128GB SSD +  1TB HDD', 'Nvidia GeForce GTX 1060', 'Windows 10', '2.2kg', 77202.7)
('Dell', 'Ultrabook', 13.3, 'IPS Panel Full HD 1920x1080', 'Intel Core i7 8550U 1.8GHz', '8GB', '256GB SSD', 'Intel UHD Graphics 620', 'Windows 10', '1.21kg', 87858.7)
('Asus', 'Gaming', 15.6, 'Full HD 1920x1080', 'AMD FX 9830P 3GHz', '8GB', '1TB HDD', 'AMD Radeon RX 560', 'Windows 10', '2.45kg', 37242.7)
('Acer', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i7 8550U 1.8GHz', '8GB', '1TB HDD', 'Nvidia GeForce MX150', 'Windows 10', '2.2kg', 36709.9)
('HP', 'Notebook', 13.3, 'Full HD 1920x1080', 'Intel Core i7 8550U 1.8GHz', '16GB', '512GB SSD', 'Intel UHD Graphics 620', 'Windows 10', '1.49kg', 63776.2)
('Dell', 'Gaming', 15.6, 'Full HD 1920x1080', 'Intel Core i5 7300HQ 2.5GHz', '8GB', '256GB SSD', 'Nvidia GeForce GTX 1060', 'Windows 10', '2.65kg', 63669.6)
('Asus', 'Ultrabook', 14.0, 'Full HD 1920x1080', 'Intel Core i7 7500U 2.7GHz', '8GB', '256GB SSD', 'Intel HD Graphics 620', 'Windows 10', '1.25kg', 55890.7)
('Acer', '2 in 1 Convertible', 13.3, 'IPS Panel Full HD / Touchscreen 1920x1080', 'Intel Core i5 8250U 1.6GHz', '8GB', '256GB SSD', 'Intel UHD Graphics 620', 'Windows 10', '1.5kg', 45128.2)
('Dell', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i7 7500U 2.7GHz', '8GB', '1TB HDD', 'AMD Radeon R5 M430', 'Linux', '2.2kg', 31962.7)
('Dell', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i3 6006U 2GHz', '4GB', '256GB SSD', 'AMD Radeon R5 M430', 'Linux', '2.2kg', 25840.8)
('Asus', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i3 7100U 2.4GHz', '6GB', '256GB SSD', 'Nvidia GeForce 920M', 'Windows 10', '2kg', 30742.6)
('HP', 'Gaming', 15.6, 'IPS Panel Full HD 1920x1080', 'Intel Core i7 7700HQ 2.8GHz', '12GB', '128GB SSD +  1TB HDD', 'Nvidia GeForce GTX 1050', 'Windows 10', '2.62kg', 66546.7)
('HP', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i7 7500U 2.7GHz', '8GB', '256GB SSD', 'AMD Radeon 530', 'Windows 10', '1.91kg', 38308.3)
('HP', 'Notebook', 15.6, 'Full HD 1920x1080', 'AMD E-Series E2-9000e 1.5GHz', '4GB', '500GB HDD', 'AMD Radeon R2', 'Windows 10', '2.1kg', 18594.7)
('Dell', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i5 8250U 1.6GHz', '8GB', '1TB HDD', 'AMD Radeon 520', 'Linux', '2.2kg', 34472.2)
('HP', 'Ultrabook', 13.3, 'IPS Panel Full HD 1920x1080', 'Intel Core i7 7500U 2.7GHz', '8GB', '256GB SSD', 'Nvidia GeForce MX150', 'Windows 10', '1.38kg', 59620.3)
('Microsoft', 'Ultrabook', 13.5, 'Touchscreen 2256x1504', 'Intel Core i5 7200U 2.5GHz', '8GB', '256GB SSD', 'Intel HD Graphics 620', 'Windows 10 S', '1.252kg', 71395.2)
('HP', 'Notebook', 14.0, 'IPS Panel Full HD 1920x1080', 'Intel Core i5 7200U 2.5GHz', '6GB', '256GB SSD', 'Nvidia GeForce 940MX', 'Windows 10', '1.58kg', 35111.5)
('Lenovo', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i3 6006U 2GHz', '4GB', '1TB HDD', 'Intel HD Graphics 520', 'Windows 10', '1.85kg', 22105.9)
('Asus', 'Ultrabook', 14.0, 'IPS Panel Full HD 1920x1080', 'Intel Core i7 7500U 2.7GHz', '8GB', '256GB SSD', 'Nvidia GeForce 940MX', 'Windows 10', '1.3kg', 63563.0)
('MSI', 'Gaming', 15.6, 'Full HD 1920x1080', 'Intel Core i7 7700HQ 2.8GHz', '16GB', '256GB SSD +  1TB HDD', 'Nvidia GeForce GTX 1050 Ti', 'Windows 10', '2.2kg', 69210.7)
('Lenovo', 'Notebook', 14.0, 'IPS Panel Full HD 1920x1080', 'Intel Core i7 7500U 2.7GHz', '8GB', '256GB SSD', 'Intel HD Graphics 620', 'Windows 10', '1.58kg', 78854.4)
('Asus', 'Ultrabook', 15.6, 'Full HD 1920x1080', 'Intel Core i7 8550U 1.8GHz', '16GB', '256GB SSD +  1TB HDD', 'Nvidia GeForce MX150', 'Windows 10', '1.5kg', 67239.4)
('Dell', 'Ultrabook', 13.3, 'Quad HD+ / Touchscreen 3200x1800', 'Intel Core i7 7560U 2.4GHz', '8GB', '256GB SSD', 'Intel Iris Plus Graphics 640', 'Windows 10', '1.23kg', 73473.1)
('Lenovo', '2 in 1 Convertible', 13.3, 'IPS Panel Full HD / Touchscreen 1920x1080', 'Intel Core i5 7200U 2.5GHz', '8GB', '256GB SSD', 'Intel HD Graphics 620', 'Windows 10', '1.37kg', 74538.7)
('HP', 'Notebook', 14.0, 'IPS Panel 1366x768', 'Intel Core i5 8250U 1.6GHz', '4GB', '500GB HDD', 'Intel UHD Graphics 620', 'Windows 10', '1.63kg', 38468.2)
('Dell', 'Ultrabook', 13.3, 'IPS Panel Full HD 1920x1080', 'Intel Core i5 8250U 1.6GHz', '8GB', '256GB SSD', 'Intel UHD Graphics 620', 'Windows 10', '1.21kg', 86793.1)
('HP', '2 in 1 Convertible', 13.3, 'IPS Panel Full HD / Touchscreen 1920x1080', 'Intel Core i5 8250U 1.6GHz', '8GB', '256GB SSD', 'Intel UHD Graphics 620', 'Windows 10', '1.26kg', 74538.2)
('HP', 'Notebook', 14.0, 'Full HD 1920x1080', 'Intel Core i7 8550U 1.8GHz', '8GB', '512GB SSD', 'Intel UHD Graphics 620', 'Windows 10', '1.63kg', 57755.5)
('Dell', 'Notebook', 15.6, 'IPS Panel Full HD 1920x1080', 'Intel Core i7 8550U 1.8GHz', '8GB', '256GB SSD +  1TB HDD', 'Nvidia GeForce 940MX', 'Windows 10', '2.16kg', 60224.0)
('Asus', 'Notebook', 17.3, 'Full HD 1920x1080', 'Intel Core i3 6006U 2GHz', '4GB', '1TB HDD', 'Nvidia GeForce 920MX', 'Windows 10', '2kg', 30049.9)
('Asus', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i7 8550U 1.8GHz', '8GB', '256GB SSD', 'Nvidia GeForce 940MX', 'Windows 10', '1.7kg', 59567.0)
('Acer', 'Notebook', 15.6, 'IPS Panel Full HD / Touchscreen 1920x1080', 'Intel Core i3 7100U 2.4GHz', '6GB', '1TB HDD', 'Intel HD Graphics 620', 'Windows 10', '2.1kg', 25521.1)
('MSI', 'Gaming', 15.6, 'Full HD 1920x1080', 'Intel Core i7 7700HQ 2.8GHz', '16GB', '256GB SSD +  2TB HDD', 'Nvidia GeForce GTX 1070', 'Windows 10', '1.8kg', 119427.0)
('Lenovo', 'Notebook', 15.6, 'Full HD 1920x1080', 'Intel Core i5 7200U 2.5GHz', '8GB', '256GB SSD', 'Nvidia GeForce 940MX', 'No OS', '2.2kg', 33513.1)
('HP', 'Notebook', 17.3, 'Full HD 1920x1080', 'Intel Core i7 8550U 1.8GHz', '16GB', '512GB SSD', 'Nvidia GeForce 930MX ', 'Windows 10', '2.5kg', 67718.9)
('Acer', 'Notebook', 15.6, '1366x768', 'AMD A9-Series 9420 3GHz', '4GB', '256GB SSD', 'AMD Radeon R5', 'Windows 10', '2.1kg', 24029.3)
('HP', 'Notebook', 15.6, '1366x768', 'Intel Celeron Dual Core N3060 1.6GHz', '4GB', '500GB HDD', 'Intel HD Graphics 400', 'No OS', '1.86kg', 13799.5)

## MongoDB

In [60]:
url = "mongodb+srv://amitkm644_db_user:12345@cluster0.zbnbf7h.mongodb.net/?appName=Cluster0"

In [ ]:
!pip install pymongo

In [62]:
import pymongo

In [63]:
client = pymongo.MongoClient(url)

In [64]:
database = client["AIML"]

In [65]:
collection = database["laptop_price"]

In [66]:
df1.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [67]:
data_dict = df1.to_dict("records")

In [68]:
data_dict

[{'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 13.3,
  'ScreenResolution': 'IPS Panel Retina Display 2560x1600',
  'Cpu': 'Intel Core i5 2.3GHz',
  'Ram': '8GB',
  'Memory': '128GB SSD',
  'Gpu': 'Intel Iris Plus Graphics 640',
  'OpSys': 'macOS',
  'Weight': '1.37kg',
  'Price': 71378.6832},
 {'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 13.3,
  'ScreenResolution': '1440x900',
  'Cpu': 'Intel Core i5 1.8GHz',
  'Ram': '8GB',
  'Memory': '128GB Flash Storage',
  'Gpu': 'Intel HD Graphics 6000',
  'OpSys': 'macOS',
  'Weight': '1.34kg',
  'Price': 47895.5232},
 {'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i5 7200U 2.5GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel HD Graphics 620',
  'OpSys': 'No OS',
  'Weight': '1.86kg',
  'Price': 30636.0},
 {'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 15.4,
  'ScreenResolution': 'IPS Panel Retina Display 2880x1800',
  'Cpu': 'Intel Core i7 2.7GHz',
  'Ram': '16GB',
  'Memory': '512GB SSD',
  'Gpu': 'AMD Radeon Pro 455',
  'OpSys': 'macOS',
  'Weight': '1.83kg',
  'Price': 135195.336},
 {'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 13.3,
  'ScreenResolution': 'IPS Panel Retina Display 2560x1600',
  'Cpu': 'Intel Core i5 3.1GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel Iris Plus Graphics 650',
  'OpSys': 'macOS',
  'Weight': '1.37kg',
  'Price': 96095.808},
 {'Company': 'Acer',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'AMD A9-Series 9420 3GHz',
  'Ram': '4GB',
  'Memory': '500GB HDD',
  'Gpu': 'AMD Radeon R5',
  'OpSys': 'Windows 10',
  'Weight': '2.1kg',
  'Price': 21312.0},
 {'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 15.4,
  'ScreenResolution': 'IPS Panel Retina Display 2880x1800',
  'Cpu': 'Intel Core i7 2.2GHz',
  'Ram': '16GB',
  'Memory': '256GB Flash Storage',
  'Gpu': 'Intel Iris Pro Graphics',
  'OpSys': 'Mac OS X',
  'Weight': '2.04kg',
  'Price': 114017.6016},
 {'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 13.3,
  'ScreenResolution': '1440x900',
  'Cpu': 'Intel Core i5 1.8GHz',
  'Ram': '8GB',
  'Memory': '256GB Flash Storage',
  'Gpu': 'Intel HD Graphics 6000',
  'OpSys': 'macOS',
  'Weight': '1.34kg',
  'Price': 61735.536},
 {'Company': 'Asus',
  'TypeName': 'Ultrabook',
  'Inches': 14.0,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i7 8550U 1.8GHz',
  'Ram': '16GB',
  'Memory': '512GB SSD',
  'Gpu': 'Nvidia GeForce MX150',
  'OpSys': 'Windows 10',
  'Weight': '1.3kg',
  'Price': 79653.6},
 {'Company': 'Acer',
  'TypeName': 'Ultrabook',
  'Inches': 14.0,
  'ScreenResolution': 'IPS Panel Full HD 1920x1080',
  'Cpu': 'Intel Core i5 8250U 1.6GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel UHD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '1.6kg',
  'Price': 41025.6},
 {'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Core i5 7200U 2.5GHz',
  'Ram': '4GB',
  'Memory': '500GB HDD',
  'Gpu': 'Intel HD Graphics 620',
  'OpSys': 'No OS',
  'Weight': '1.86kg',
  'Price': 20986.992},
 {'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i3 6006U 2GHz',
  'Ram': '4GB',
  'Memory': '500GB HDD',
  'Gpu': 'Intel HD Graphics 520',
  'OpSys': 'No OS',
  'Weight': '1.86kg',
  'Price': 18381.0672},
 {'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 15.4,
  'ScreenResolution': 'IPS Panel Retina Display 2880x1800',
  'Cpu': 'Intel Core i7 2.8GHz',
  'Ram': '16GB',
  'Memory': '256GB SSD',
  'Gpu': 'AMD Radeon Pro 555',
  'OpSys': 'macOS',
  'Weight': '1.83kg',
  'Price': 130001.6016},
 {'Company': 'Dell',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i3 6006U 2GHz',
  'Ram': '4GB',
  'Memory': '256GB SSD',
  'Gpu': 'AMD Radeon R5 M430',
  'OpSys': 'Windows 10',
  'Weight': '2.2kg',
  'Price': 26581.392},
 {'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 12.0,
  'ScreenResolution': 'IPS Panel Retina Display 2304x1440',
  'Cpu': 'Intel Core M m3 1.2GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel HD Graphics 615',
  'OpSys': 'macOS',
  'Weight': '0.92kg',
  'Price': 67260.672},
 {'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 13.3,
  'ScreenResolution': 'IPS Panel Retina Display 2560x1600',
  'Cpu': 'Intel Core i5 2.3GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel Iris Plus Graphics 640',
  'OpSys': 'macOS',
  'Weight': '1.37kg',
  'Price': 80908.344},
 {'Company': 'Dell',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i7 7500U 2.7GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'AMD Radeon R5 M430',
  'OpSys': 'Windows 10',
  'Weight': '2.2kg',
  'Price': 39693.6},
 {'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 15.4,
  'ScreenResolution': 'IPS Panel Retina Display 2880x1800',
  'Cpu': 'Intel Core i7 2.9GHz',
  'Ram': '16GB',
  'Memory': '512GB SSD',
  'Gpu': 'AMD Radeon Pro 560',
  'OpSys': 'macOS',
  'Weight': '1.83kg',
  'Price': 152274.24},
 {'Company': 'Lenovo',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i3 7100U 2.4GHz',
  'Ram': '8GB',
  'Memory': '1TB HDD',
  'Gpu': 'Nvidia GeForce 940MX',
  'OpSys': 'No OS',
  'Weight': '2.2kg',
  'Price': 26586.72},
 {'Company': 'Dell',
  'TypeName': 'Ultrabook',
  'Inches': 13.3,
  'ScreenResolution': 'IPS Panel Full HD / Touchscreen 1920x1080',
  'Cpu': 'Intel Core i5 8250U 1.6GHz',
  'Ram': '8GB',
  'Memory': '128GB SSD',
  'Gpu': 'Intel UHD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '1.22kg',
  'Price': 52161.12},
 {'Company': 'Asus',
  'TypeName': 'Netbook',
  'Inches': 11.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Atom x5-Z8350 1.44GHz',
  'Ram': '2GB',
  'Memory': '32GB Flash Storage',
  'Gpu': 'Intel HD Graphics 400',
  'OpSys': 'Windows 10',
  'Weight': '0.98kg',
  'Price': 10224.432},
 {'Company': 'Lenovo',
  'TypeName': 'Gaming',
  'Inches': 15.6,
  'ScreenResolution': 'IPS Panel Full HD 1920x1080',
  'Cpu': 'Intel Core i5 7300HQ 2.5GHz',
  'Ram': '8GB',
  'Memory': '128GB SSD +  1TB HDD',
  'Gpu': 'Nvidia GeForce GTX 1050',
  'OpSys': 'Windows 10',
  'Weight': '2.5kg',
  'Price': 53226.72},
 {'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'AMD E-Series E2-9000e 1.5GHz',
  'Ram': '4GB',
  'Memory': '500GB HDD',
  'Gpu': 'AMD Radeon R2',
  'OpSys': 'No OS',
  'Weight': '1.86kg',
  'Price': 13746.24},
 {'Company': 'Dell',
  'TypeName': '2 in 1 Convertible',
  'Inches': 13.3,
  'ScreenResolution': 'Full HD / Touchscreen 1920x1080',
  'Cpu': 'Intel Core i5 8250U 1.6GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel UHD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '1.62kg',
  'Price': 43636.32},
 {'Company': 'HP',
  'TypeName': 'Ultrabook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i7 8550U 1.8GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel HD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '1.91kg',
  'Price': 35111.52},
 {'Company': 'Dell',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Core i3 6006U 2GHz',
  'Ram': '4GB',
  'Memory': '1TB HDD',
  'Gpu': 'Intel HD Graphics 520',
  'OpSys': 'Windows 10',
  'Weight': '2.3kg',
  'Price': 22305.1392},
 {'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 13.3,
  'ScreenResolution': '1440x900',
  'Cpu': 'Intel Core i5 1.6GHz',
  'Ram': '8GB',
  'Memory': '128GB Flash Storage',
  'Gpu': 'Intel HD Graphics 6000',
  'OpSys': 'Mac OS X',
  'Weight': '1.35kg',
  'Price': 58554.72},
 {'Company': 'Dell',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i5 8250U 1.6GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'AMD Radeon 530',
  'OpSys': 'Windows 10',
  'Weight': '2.2kg',
  'Price': 42624.0},
 {'Company': 'Dell',
  'TypeName': 'Ultrabook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i7 8650U 1.9GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD +  256GB SSD',
  'Gpu': 'Intel UHD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '1.88kg',
  'Price': 69157.44},
 {'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 17.3,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i5 8250U 1.6GHz',
  'Ram': '8GB',
  'Memory': '1TB HDD',
  'Gpu': 'Nvidia GeForce 930MX',
  'OpSys': 'Windows 10',
  'Weight': '2.5kg',
  'Price': 47738.88},
 {'Company': 'Chuwi',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Atom x5-Z8300 1.44GHz',
  'Ram': '4GB',
  'Memory': '64GB Flash Storage',
  'Gpu': 'Intel HD Graphics',
  'OpSys': 'Windows 10',
  'Weight': '1.89kg',
  'Price': 13053.0672},
 {'Company': 'Asus',
  'TypeName': 'Notebook',
  'Inches': 14.0,
  'ScreenResolution': '1366x768',
  'Cpu': 'AMD E-Series E2-6110 1.5GHz',
  'Ram': '2GB',
  'Memory': '32GB Flash Storage',
  'Gpu': 'AMD Radeon R2',
  'OpSys': 'Windows 10',
  'Weight': '1.65kg',
  'Price': 10602.72},
 {'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 17.3,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'AMD A6-Series 9220 2.5GHz',
  'Ram': '4GB',
  'Memory': '500GB HDD',
  'Gpu': 'AMD Radeon 530',
  'OpSys': 'Windows 10',
  'Weight': '2.71kg',
  'Price': 23389.92},
 {'Company': 'Dell',
  'TypeName': 'Ultrabook',
  'Inches': 13.3,
  'ScreenResolution': 'Touchscreen / Quad HD+ 3200x1800',
  'Cpu': 'Intel Core i7 8550U 1.8GHz',
  'Ram': '16GB',
  'Memory': '512GB SSD',
  'Gpu': 'Intel UHD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '1.2kg',
  'Price': 99580.32},
 {'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 13.3,
  'ScreenResolution': '1440x900',
  'Cpu': 'Intel Core i5 1.6GHz',
  'Ram': '8GB',
  'Memory': '256GB Flash Storage',
  'Gpu': 'Intel HD Graphics 6000',
  'OpSys': 'Mac OS X',
  'Weight': '1.35kg',
  'Price': 53173.44},
 {'Company': 'Lenovo',
  'TypeName': 'Notebook',
  'Inches': 14.0,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Celeron Dual Core N3350 1.1GHz',
  'Ram': '4GB',
  'Memory': '64GB Flash Storage',
  'Gpu': 'Intel HD Graphics 500',
  'OpSys': 'Windows 10',
  'Weight': '1.44kg',
  'Price': 13266.72},
 {'Company': 'Acer',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Core i3 7130U 2.7GHz',
  'Ram': '4GB',
  'Memory': '1TB HDD',
  'Gpu': 'Intel HD Graphics 620',
  'OpSys': 'Linux',
  'Weight': '2.1kg',
  'Price': 19553.76},
 {'Company': 'Dell',
  'TypeName': 'Notebook',
  'Inches': 17.3,
  'ScreenResolution': 'IPS Panel Full HD 1920x1080',
  'Cpu': 'Intel Core i5 8250U 1.6GHz',
  'Ram': '8GB',
  'Memory': '128GB SSD +  1TB HDD',
  'Gpu': 'AMD Radeon 530',
  'OpSys': 'Windows 10',
  'Weight': '2.8kg',
  'Price': 52161.12},
 {'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Core i5 7200U 2.5GHz',
  'Ram': '4GB',
  'Memory': '1TB HDD',
  'Gpu': 'Intel HD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '1.86kg',
  'Price': 26037.4032},
 {'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i5 8250U 1.6GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Nvidia GeForce 930MX ',
  'OpSys': 'Windows 10',
  'Weight': '2.1kg',
  'Price': 46833.12},
 {'Company': 'Asus',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i3 6006U 2GHz',
  'Ram': '4GB',
  'Memory': '1TB HDD',
  'Gpu': 'Intel HD Graphics 620',
  'OpSys': 'Linux',
  'Weight': '2kg',
  'Price': 20725.92},
 {'Company': 'Dell',
  'TypeName': 'Gaming',
  'Inches': 15.6,
  'ScreenResolution': 'IPS Panel Full HD 1920x1080',
  'Cpu': 'Intel Core i7 7700HQ 2.8GHz',
  'Ram': '16GB',
  'Memory': '256GB SSD +  1TB HDD',
  'Gpu': 'Nvidia GeForce GTX 1060',
  'OpSys': 'Windows 10',
  'Weight': '2.65kg',
  'Price': 79866.72},
 {'Company': 'Asus',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Core i5 7200U 2.5GHz',
  'Ram': '8GB',
  'Memory': '1TB HDD',
  'Gpu': 'Nvidia GeForce 940MX',
  'OpSys': 'Linux',
  'Weight': '2.3kg',
  'Price': 27864.9072},
 {'Company': 'Acer',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'IPS Panel Full HD 1920x1080',
  'Cpu': 'Intel Core i5 8250U 1.6GHz',
  'Ram': '4GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel UHD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '2.2kg',
  'Price': 36336.96},
 {'Company': 'Dell',
  'TypeName': '2 in 1 Convertible',
  'Inches': 17.3,
  'ScreenResolution': 'Full HD / Touchscreen 1920x1080',
  'Cpu': 'Intel Core i5 8250U 1.6GHz',
  'Ram': '12GB',
  'Memory': '1TB HDD',
  'Gpu': 'Nvidia GeForce 150MX',
  'OpSys': 'Windows 10',
  'Weight': '2.77kg',
  'Price': 53226.72},
 {'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 13.3,
  'ScreenResolution': 'IPS Panel Retina Display 2560x1600',
  'Cpu': 'Intel Core i5 2.0GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel Iris Graphics 540',
  'OpSys': 'macOS',
  'Weight': '1.37kg',
  'Price': 75604.32},
 {'Company': 'Lenovo',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Core i3 6006U 2GHz',
  'Ram': '4GB',
  'Memory': '128GB SSD',
  'Gpu': 'Intel HD Graphics 520',
  'OpSys': 'No OS',
  'Weight': '2.2kg',
  'Price': 19660.32},
 {'Company': 'Asus',
  'TypeName': 'Gaming',
  'Inches': 17.3,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'AMD Ryzen 1700 3GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD +  1TB HDD',
  'Gpu': 'AMD Radeon RX 580',
  'OpSys': 'Windows 10',
  'Weight': '3.2kg',
  'Price': 69210.72},
 {'Company': 'Dell',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i5 7200U 2.5GHz',
  'Ram': '4GB',
  'Memory': '256GB SSD',
  'Gpu': 'AMD Radeon R5 M430',
  'OpSys': 'Windows 10',
  'Weight': '2.3kg',
  'Price': 34045.92},
 {'Company': 'Asus',
  'TypeName': 'Notebook',
  'Inches': 17.3,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Pentium Quad Core N4200 1.1GHz',
  'Ram': '4GB',
  'Memory': '1TB HDD',
  'Gpu': 'Nvidia GeForce 920MX',
  'OpSys': 'Windows 10',
  'Weight': '2.8kg',
  'Price': 24828.48},
 {'Company': 'Lenovo',
  'TypeName': '2 in 1 Convertible',
  'Inches': 10.1,
  'ScreenResolution': 'IPS Panel Touchscreen 1920x1200',
  'Cpu': 'Intel Atom x5-Z8550 1.44GHz',
  'Ram': '4GB',
  'Memory': '64GB Flash Storage',
  'Gpu': 'Intel HD Graphics 400',
  'OpSys': 'Android',
  'Weight': '0.69kg',
  'Price': 16996.32},
 {'Company': 'Acer',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'IPS Panel Full HD 1920x1080',
  'Cpu': 'Intel Core i7 8550U 1.8GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Nvidia GeForce MX150',
  'OpSys': 'Windows 10',
  'Weight': '2.2kg',
  'Price': 44808.48},
 {'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'AMD A6-Series 9220 2.5GHz',
  'Ram': '4GB',
  'Memory': '256GB SSD',
  'Gpu': 'AMD Radeon R4 Graphics',
  'OpSys': 'Windows 10',
  'Weight': '1.86kg',
  'Price': 21231.5472},
 {'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 13.3,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i7 8550U 1.8GHz',
  'Ram': '8GB',
  'Memory': '512GB SSD',
  'Gpu': 'Intel UHD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '1.49kg',
  'Price': 58767.84},
 {'Company': 'Acer',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Core i3 7100U 2.4GHz',
  'Ram': '4GB',
  'Memory': '1TB HDD',
  'Gpu': 'Intel HD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '2.4kg',
  'Price': 20459.52},
 {'Company': 'Dell',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i7 8550U 1.8GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'AMD Radeon 520',
  'OpSys': 'Windows 10',
  'Weight': '2.13kg',
  'Price': 40908.384},
 {'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i3 6006U 2GHz',
  'Ram': '4GB',
  'Memory': '128GB SSD',
  'Gpu': 'Intel HD Graphics 520',
  'OpSys': 'Windows 10',
  'Weight': '1.91kg',
  'Price': 23389.92},
 {'Company': 'Asus',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Core i5 7200U 2.5GHz',
  'Ram': '4GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel HD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '2kg',
  'Price': 31232.2032},
 {'Company': 'MSI',
  'TypeName': 'Gaming',
  'Inches': 17.3,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i7 7700HQ 2.8GHz',
  'Ram': '16GB',
  'Memory': '256GB SSD +  2TB HDD',
  'Gpu': 'Nvidia GeForce GTX 1070',
  'OpSys': 'Windows 10',
  'Weight': '2.43kg',
  'Price': 130482.72},
 {'Company': 'Asus',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i3 6006U 2GHz',
  'Ram': '4GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel HD Graphics 520',
  'OpSys': 'Linux',
  'Weight': '2kg',
  'Price': 22111.2},
 {'Company': 'Dell',
  'TypeName': 'Notebook',
  'Inches': 17.3,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i7 8550U 1.8GHz',
  'Ram': '16GB',
  'Memory': '256GB SSD +  2TB HDD',
  'Gpu': 'AMD Radeon 530',
  'OpSys': 'Windows 10',
  'Weight': '2.8kg',
  'Price': 69210.72},
 {'Company': 'Dell',
  'TypeName': 'Ultrabook',
  'Inches': 14.0,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i5 8250U 1.6GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel UHD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '1.7kg',
  'Price': 46833.12},
 {'Company': 'Lenovo',
  'TypeName': 'Notebook',
  'Inches': 14.0,
  'ScreenResolution': 'IPS Panel Full HD 1920x1080',
  'Cpu': 'Intel Core i3 7130U 2.7GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel HD Graphics 620',
  'OpSys': 'No OS',
  'Weight': '1.7kg',
  'Price': 31914.72},
 {'Company': 'Asus',
  'TypeName': 'Notebook',
  'Inches': 14.0,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i5 8250U 1.6GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel UHD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '1.4kg',
  'Price': 50136.48},
 {'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i5 7200U 2.5GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel HD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '1.86kg',
  'Price': 36763.2},
 {'Company': 'Asus',
  'TypeName': 'Ultrabook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i7 7700HQ 2.8GHz',
  'Ram': '16GB',
  'Memory': '512GB SSD',
  'Gpu': 'Nvidia GeForce GTX 1050 Ti',
  'OpSys': 'Windows 10',
  'Weight': '1.8kg',
  'Price': 105654.24},
 {'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Core i3 6006U 2GHz',
  'Ram': '4GB',
  'Memory': '500GB HDD',
  'Gpu': 'AMD Radeon 520',
  'OpSys': 'Windows 10',
  'Weight': '1.86kg',
  'Price': 23373.4032},
 {'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 14.0,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Celeron Dual Core N3060 1.6GHz',
  'Ram': '4GB',
  'Memory': '32GB SSD',
  'Gpu': 'Intel HD Graphics 400',
  'OpSys': 'Windows 10',
  'Weight': '1.44kg',
  'Price': 12201.12},
 {'Company': 'Lenovo',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',

In [69]:
# Insert into MongoDB
collection.insert_many(data_dict)

print("CSV data has been inserted into MongoDB!")

CSV data has been inserted into MongoDB!

In [75]:
cursor = collection.find()

In [71]:
cursor

In [72]:
list(cursor)

[{'_id': ObjectId('698d5b64d929263d0f2a0a5f'),
  'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 13.3,
  'ScreenResolution': 'IPS Panel Retina Display 2560x1600',
  'Cpu': 'Intel Core i5 2.3GHz',
  'Ram': '8GB',
  'Memory': '128GB SSD',
  'Gpu': 'Intel Iris Plus Graphics 640',
  'OpSys': 'macOS',
  'Weight': '1.37kg',
  'Price': 71378.6832},
 {'_id': ObjectId('698d5b64d929263d0f2a0a60'),
  'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 13.3,
  'ScreenResolution': '1440x900',
  'Cpu': 'Intel Core i5 1.8GHz',
  'Ram': '8GB',
  'Memory': '128GB Flash Storage',
  'Gpu': 'Intel HD Graphics 6000',
  'OpSys': 'macOS',
  'Weight': '1.34kg',
  'Price': 47895.5232},
 {'_id': ObjectId('698d5b64d929263d0f2a0a61'),
  'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i5 7200U 2.5GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel HD Graphics 620',
  'OpSys': 'No OS',
  'Weight': '1.86kg',
  'Price': 30636.0},
 {'_id': ObjectId('698d5b64d929263d0f2a0a62'),
  'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 15.4,
  'ScreenResolution': 'IPS Panel Retina Display 2880x1800',
  'Cpu': 'Intel Core i7 2.7GHz',
  'Ram': '16GB',
  'Memory': '512GB SSD',
  'Gpu': 'AMD Radeon Pro 455',
  'OpSys': 'macOS',
  'Weight': '1.83kg',
  'Price': 135195.336},
 {'_id': ObjectId('698d5b64d929263d0f2a0a63'),
  'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 13.3,
  'ScreenResolution': 'IPS Panel Retina Display 2560x1600',
  'Cpu': 'Intel Core i5 3.1GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel Iris Plus Graphics 650',
  'OpSys': 'macOS',
  'Weight': '1.37kg',
  'Price': 96095.808},
 {'_id': ObjectId('698d5b64d929263d0f2a0a64'),
  'Company': 'Acer',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'AMD A9-Series 9420 3GHz',
  'Ram': '4GB',
  'Memory': '500GB HDD',
  'Gpu': 'AMD Radeon R5',
  'OpSys': 'Windows 10',
  'Weight': '2.1kg',
  'Price': 21312.0},
 {'_id': ObjectId('698d5b64d929263d0f2a0a65'),
  'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 15.4,
  'ScreenResolution': 'IPS Panel Retina Display 2880x1800',
  'Cpu': 'Intel Core i7 2.2GHz',
  'Ram': '16GB',
  'Memory': '256GB Flash Storage',
  'Gpu': 'Intel Iris Pro Graphics',
  'OpSys': 'Mac OS X',
  'Weight': '2.04kg',
  'Price': 114017.6016},
 {'_id': ObjectId('698d5b64d929263d0f2a0a66'),
  'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 13.3,
  'ScreenResolution': '1440x900',
  'Cpu': 'Intel Core i5 1.8GHz',
  'Ram': '8GB',
  'Memory': '256GB Flash Storage',
  'Gpu': 'Intel HD Graphics 6000',
  'OpSys': 'macOS',
  'Weight': '1.34kg',
  'Price': 61735.536},
 {'_id': ObjectId('698d5b64d929263d0f2a0a67'),
  'Company': 'Asus',
  'TypeName': 'Ultrabook',
  'Inches': 14.0,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i7 8550U 1.8GHz',
  'Ram': '16GB',
  'Memory': '512GB SSD',
  'Gpu': 'Nvidia GeForce MX150',
  'OpSys': 'Windows 10',
  'Weight': '1.3kg',
  'Price': 79653.6},
 {'_id': ObjectId('698d5b64d929263d0f2a0a68'),
  'Company': 'Acer',
  'TypeName': 'Ultrabook',
  'Inches': 14.0,
  'ScreenResolution': 'IPS Panel Full HD 1920x1080',
  'Cpu': 'Intel Core i5 8250U 1.6GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel UHD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '1.6kg',
  'Price': 41025.6},
 {'_id': ObjectId('698d5b64d929263d0f2a0a69'),
  'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Core i5 7200U 2.5GHz',
  'Ram': '4GB',
  'Memory': '500GB HDD',
  'Gpu': 'Intel HD Graphics 620',
  'OpSys': 'No OS',
  'Weight': '1.86kg',
  'Price': 20986.992},
 {'_id': ObjectId('698d5b64d929263d0f2a0a6a'),
  'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i3 6006U 2GHz',
  'Ram': '4GB',
  'Memory': '500GB HDD',
  'Gpu': 'Intel HD Graphics 520',
  'OpSys': 'No OS',
  'Weight': '1.86kg',
  'Price': 18381.0672},
 {'_id': ObjectId('698d5b64d929263d0f2a0a6b'),
  'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 15.4,
  'ScreenResolution': 'IPS Panel Retina Display 2880x1800',
  'Cpu': 'Intel Core i7 2.8GHz',
  'Ram': '16GB',
  'Memory': '256GB SSD',
  'Gpu': 'AMD Radeon Pro 555',
  'OpSys': 'macOS',
  'Weight': '1.83kg',
  'Price': 130001.6016},
 {'_id': ObjectId('698d5b64d929263d0f2a0a6c'),
  'Company': 'Dell',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i3 6006U 2GHz',
  'Ram': '4GB',
  'Memory': '256GB SSD',
  'Gpu': 'AMD Radeon R5 M430',
  'OpSys': 'Windows 10',
  'Weight': '2.2kg',
  'Price': 26581.392},
 {'_id': ObjectId('698d5b64d929263d0f2a0a6d'),
  'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 12.0,
  'ScreenResolution': 'IPS Panel Retina Display 2304x1440',
  'Cpu': 'Intel Core M m3 1.2GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel HD Graphics 615',
  'OpSys': 'macOS',
  'Weight': '0.92kg',
  'Price': 67260.672},
 {'_id': ObjectId('698d5b64d929263d0f2a0a6e'),
  'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 13.3,
  'ScreenResolution': 'IPS Panel Retina Display 2560x1600',
  'Cpu': 'Intel Core i5 2.3GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel Iris Plus Graphics 640',
  'OpSys': 'macOS',
  'Weight': '1.37kg',
  'Price': 80908.344},
 {'_id': ObjectId('698d5b64d929263d0f2a0a6f'),
  'Company': 'Dell',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i7 7500U 2.7GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'AMD Radeon R5 M430',
  'OpSys': 'Windows 10',
  'Weight': '2.2kg',
  'Price': 39693.6},
 {'_id': ObjectId('698d5b64d929263d0f2a0a70'),
  'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 15.4,
  'ScreenResolution': 'IPS Panel Retina Display 2880x1800',
  'Cpu': 'Intel Core i7 2.9GHz',
  'Ram': '16GB',
  'Memory': '512GB SSD',
  'Gpu': 'AMD Radeon Pro 560',
  'OpSys': 'macOS',
  'Weight': '1.83kg',
  'Price': 152274.24},
 {'_id': ObjectId('698d5b64d929263d0f2a0a71'),
  'Company': 'Lenovo',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i3 7100U 2.4GHz',
  'Ram': '8GB',
  'Memory': '1TB HDD',
  'Gpu': 'Nvidia GeForce 940MX',
  'OpSys': 'No OS',
  'Weight': '2.2kg',
  'Price': 26586.72},
 {'_id': ObjectId('698d5b64d929263d0f2a0a72'),
  'Company': 'Dell',
  'TypeName': 'Ultrabook',
  'Inches': 13.3,
  'ScreenResolution': 'IPS Panel Full HD / Touchscreen 1920x1080',
  'Cpu': 'Intel Core i5 8250U 1.6GHz',
  'Ram': '8GB',
  'Memory': '128GB SSD',
  'Gpu': 'Intel UHD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '1.22kg',
  'Price': 52161.12},
 {'_id': ObjectId('698d5b64d929263d0f2a0a73'),
  'Company': 'Asus',
  'TypeName': 'Netbook',
  'Inches': 11.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Atom x5-Z8350 1.44GHz',
  'Ram': '2GB',
  'Memory': '32GB Flash Storage',
  'Gpu': 'Intel HD Graphics 400',
  'OpSys': 'Windows 10',
  'Weight': '0.98kg',
  'Price': 10224.432},
 {'_id': ObjectId('698d5b64d929263d0f2a0a74'),
  'Company': 'Lenovo',
  'TypeName': 'Gaming',
  'Inches': 15.6,
  'ScreenResolution': 'IPS Panel Full HD 1920x1080',
  'Cpu': 'Intel Core i5 7300HQ 2.5GHz',
  'Ram': '8GB',
  'Memory': '128GB SSD +  1TB HDD',
  'Gpu': 'Nvidia GeForce GTX 1050',
  'OpSys': 'Windows 10',
  'Weight': '2.5kg',
  'Price': 53226.72},
 {'_id': ObjectId('698d5b64d929263d0f2a0a75'),
  'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'AMD E-Series E2-9000e 1.5GHz',
  'Ram': '4GB',
  'Memory': '500GB HDD',
  'Gpu': 'AMD Radeon R2',
  'OpSys': 'No OS',
  'Weight': '1.86kg',
  'Price': 13746.24},
 {'_id': ObjectId('698d5b64d929263d0f2a0a76'),
  'Company': 'Dell',
  'TypeName': '2 in 1 Convertible',
  'Inches': 13.3,
  'ScreenResolution': 'Full HD / Touchscreen 1920x1080',
  'Cpu': 'Intel Core i5 8250U 1.6GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel UHD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '1.62kg',
  'Price': 43636.32},
 {'_id': ObjectId('698d5b64d929263d0f2a0a77'),
  'Company': 'HP',
  'TypeName': 'Ultrabook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i7 8550U 1.8GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel HD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '1.91kg',
  'Price': 35111.52},
 {'_id': ObjectId('698d5b64d929263d0f2a0a78'),
  'Company': 'Dell',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Core i3 6006U 2GHz',
  'Ram': '4GB',
  'Memory': '1TB HDD',
  'Gpu': 'Intel HD Graphics 520',
  'OpSys': 'Windows 10',
  'Weight': '2.3kg',
  'Price': 22305.1392},
 {'_id': ObjectId('698d5b64d929263d0f2a0a79'),
  'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 13.3,
  'ScreenResolution': '1440x900',
  'Cpu': 'Intel Core i5 1.6GHz',
  'Ram': '8GB',
  'Memory': '128GB Flash Storage',
  'Gpu': 'Intel HD Graphics 6000',
  'OpSys': 'Mac OS X',
  'Weight': '1.35kg',
  'Price': 58554.72},
 {'_id': ObjectId('698d5b64d929263d0f2a0a7a'),
  'Company': 'Dell',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i5 8250U 1.6GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'AMD Radeon 530',
  'OpSys': 'Windows 10',
  'Weight': '2.2kg',
  'Price': 42624.0},
 {'_id': ObjectId('698d5b64d929263d0f2a0a7b'),
  'Company': 'Dell',
  'TypeName': 'Ultrabook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i7 8650U 1.9GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD +  256GB SSD',
  'Gpu': 'Intel UHD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '1.88kg',
  'Price': 69157.44},
 {'_id': ObjectId('698d5b64d929263d0f2a0a7c'),
  'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 17.3,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i5 8250U 1.6GHz',
  'Ram': '8GB',
  'Memory': '1TB HDD',
  'Gpu': 'Nvidia GeForce 930MX',
  'OpSys': 'Windows 10',
  'Weight': '2.5kg',
  'Price': 47738.88},
 {'_id': ObjectId('698d5b64d929263d0f2a0a7d'),
  'Company': 'Chuwi',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Atom x5-Z8300 1.44GHz',
  'Ram': '4GB',
  'Memory': '64GB Flash Storage',
  'Gpu': 'Intel HD Graphics',
  'OpSys': 'Windows 10',
  'Weight': '1.89kg',
  'Price': 13053.0672},
 {'_id': ObjectId('698d5b64d929263d0f2a0a7e'),
  'Company': 'Asus',
  'TypeName': 'Notebook',
  'Inches': 14.0,
  'ScreenResolution': '1366x768',
  'Cpu': 'AMD E-Series E2-6110 1.5GHz',
  'Ram': '2GB',
  'Memory': '32GB Flash Storage',
  'Gpu': 'AMD Radeon R2',
  'OpSys': 'Windows 10',
  'Weight': '1.65kg',
  'Price': 10602.72},
 {'_id': ObjectId('698d5b64d929263d0f2a0a7f'),
  'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 17.3,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'AMD A6-Series 9220 2.5GHz',
  'Ram': '4GB',
  'Memory': '500GB HDD',
  'Gpu': 'AMD Radeon 530',
  'OpSys': 'Windows 10',
  'Weight': '2.71kg',
  'Price': 23389.92},
 {'_id': ObjectId('698d5b64d929263d0f2a0a80'),
  'Company': 'Dell',
  'TypeName': 'Ultrabook',
  'Inches': 13.3,
  'ScreenResolution': 'Touchscreen / Quad HD+ 3200x1800',
  'Cpu': 'Intel Core i7 8550U 1.8GHz',
  'Ram': '16GB',
  'Memory': '512GB SSD',
  'Gpu': 'Intel UHD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '1.2kg',
  'Price': 99580.32},
 {'_id': ObjectId('698d5b64d929263d0f2a0a81'),
  'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 13.3,
  'ScreenResolution': '1440x900',
  'Cpu': 'Intel Core i5 1.6GHz',
  'Ram': '8GB',
  'Memory': '256GB Flash Storage',
  'Gpu': 'Intel HD Graphics 6000',
  'OpSys': 'Mac OS X',
  'Weight': '1.35kg',
  'Price': 53173.44},
 {'_id': ObjectId('698d5b64d929263d0f2a0a82'),
  'Company': 'Lenovo',
  'TypeName': 'Notebook',
  'Inches': 14.0,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Celeron Dual Core N3350 1.1GHz',
  'Ram': '4GB',
  'Memory': '64GB Flash Storage',
  'Gpu': 'Intel HD Graphics 500',
  'OpSys': 'Windows 10',
  'Weight': '1.44kg',
  'Price': 13266.72},
 {'_id': ObjectId('698d5b64d929263d0f2a0a83'),
  'Company': 'Acer',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Core i3 7130U 2.7GHz',
  'Ram': '4GB',
  'Memory': '1TB HDD',
  'Gpu': 'Intel HD Graphics 620',
  'OpSys': 'Linux',
  'Weight': '2.1kg',
  'Price': 19553.76},
 {'_id': ObjectId('698d5b64d929263d0f2a0a84'),
  'Company': 'Dell',
  'TypeName': 'Notebook',
  'Inches': 17.3,
  'ScreenResolution': 'IPS Panel Full HD 1920x1080',
  'Cpu': 'Intel Core i5 8250U 1.6GHz',
  'Ram': '8GB',
  'Memory': '128GB SSD +  1TB HDD',
  'Gpu': 'AMD Radeon 530',
  'OpSys': 'Windows 10',
  'Weight': '2.8kg',
  'Price': 52161.12},
 {'_id': ObjectId('698d5b64d929263d0f2a0a85'),
  'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Core i5 7200U 2.5GHz',
  'Ram': '4GB',
  'Memory': '1TB HDD',
  'Gpu': 'Intel HD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '1.86kg',
  'Price': 26037.4032},
 {'_id': ObjectId('698d5b64d929263d0f2a0a86'),
  'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i5 8250U 1.6GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Nvidia GeForce 930MX ',
  'OpSys': 'Windows 10',
  'Weight': '2.1kg',
  'Price': 46833.12},
 {'_id': ObjectId('698d5b64d929263d0f2a0a87'),
  'Company': 'Asus',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i3 6006U 2GHz',
  'Ram': '4GB',
  'Memory': '1TB HDD',
  'Gpu': 'Intel HD Graphics 620',
  'OpSys': 'Linux',
  'Weight': '2kg',
  'Price': 20725.92},
 {'_id': ObjectId('698d5b64d929263d0f2a0a88'),
  'Company': 'Dell',
  'TypeName': 'Gaming',
  'Inches': 15.6,
  'ScreenResolution': 'IPS Panel Full HD 1920x1080',
  'Cpu': 'Intel Core i7 7700HQ 2.8GHz',
  'Ram': '16GB',
  'Memory': '256GB SSD +  1TB HDD',
  'Gpu': 'Nvidia GeForce GTX 1060',
  'OpSys': 'Windows 10',
  'Weight': '2.65kg',
  'Price': 79866.72},
 {'_id': ObjectId('698d5b64d929263d0f2a0a89'),
  'Company': 'Asus',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Core i5 7200U 2.5GHz',
  'Ram': '8GB',
  'Memory': '1TB HDD',
  'Gpu': 'Nvidia GeForce 940MX',
  'OpSys': 'Linux',
  'Weight': '2.3kg',
  'Price': 27864.9072},
 {'_id': ObjectId('698d5b64d929263d0f2a0a8a'),
  'Company': 'Acer',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'IPS Panel Full HD 1920x1080',
  'Cpu': 'Intel Core i5 8250U 1.6GHz',
  'Ram': '4GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel UHD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '2.2kg',
  'Price': 36336.96},
 {'_id': ObjectId('698d5b64d929263d0f2a0a8b'),
  'Company': 'Dell',
  'TypeName': '2 in 1 Convertible',
  'Inches': 17.3,
  'ScreenResolution': 'Full HD / Touchscreen 1920x1080',
  'Cpu': 'Intel Core i5 8250U 1.6GHz',
  'Ram': '12GB',
  'Memory': '1TB HDD',
  'Gpu': 'Nvidia GeForce 150MX',
  'OpSys': 'Windows 10',
  'Weight': '2.77kg',
  'Price': 53226.72},
 {'_id': ObjectId('698d5b64d929263d0f2a0a8c'),
  'Company': 'Apple',
  'TypeName': 'Ultrabook',
  'Inches': 13.3,
  'ScreenResolution': 'IPS Panel Retina Display 2560x1600',
  'Cpu': 'Intel Core i5 2.0GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel Iris Graphics 540',
  'OpSys': 'macOS',
  'Weight': '1.37kg',
  'Price': 75604.32},
 {'_id': ObjectId('698d5b64d929263d0f2a0a8d'),
  'Company': 'Lenovo',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Core i3 6006U 2GHz',
  'Ram': '4GB',
  'Memory': '128GB SSD',
  'Gpu': 'Intel HD Graphics 520',
  'OpSys': 'No OS',
  'Weight': '2.2kg',
  'Price': 19660.32},
 {'_id': ObjectId('698d5b64d929263d0f2a0a8e'),
  'Company': 'Asus',
  'TypeName': 'Gaming',
  'Inches': 17.3,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'AMD Ryzen 1700 3GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD +  1TB HDD',
  'Gpu': 'AMD Radeon RX 580',
  'OpSys': 'Windows 10',
  'Weight': '3.2kg',
  'Price': 69210.72},
 {'_id': ObjectId('698d5b64d929263d0f2a0a8f'),
  'Company': 'Dell',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i5 7200U 2.5GHz',
  'Ram': '4GB',
  'Memory': '256GB SSD',
  'Gpu': 'AMD Radeon R5 M430',
  'OpSys': 'Windows 10',
  'Weight': '2.3kg',
  'Price': 34045.92},
 {'_id': ObjectId('698d5b64d929263d0f2a0a90'),
  'Company': 'Asus',
  'TypeName': 'Notebook',
  'Inches': 17.3,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Pentium Quad Core N4200 1.1GHz',
  'Ram': '4GB',
  'Memory': '1TB HDD',
  'Gpu': 'Nvidia GeForce 920MX',
  'OpSys': 'Windows 10',
  'Weight': '2.8kg',
  'Price': 24828.48},
 {'_id': ObjectId('698d5b64d929263d0f2a0a91'),
  'Company': 'Lenovo',
  'TypeName': '2 in 1 Convertible',
  'Inches': 10.1,
  'ScreenResolution': 'IPS Panel Touchscreen 1920x1200',
  'Cpu': 'Intel Atom x5-Z8550 1.44GHz',
  'Ram': '4GB',
  'Memory': '64GB Flash Storage',
  'Gpu': 'Intel HD Graphics 400',
  'OpSys': 'Android',
  'Weight': '0.69kg',
  'Price': 16996.32},
 {'_id': ObjectId('698d5b64d929263d0f2a0a92'),
  'Company': 'Acer',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'IPS Panel Full HD 1920x1080',
  'Cpu': 'Intel Core i7 8550U 1.8GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'Nvidia GeForce MX150',
  'OpSys': 'Windows 10',
  'Weight': '2.2kg',
  'Price': 44808.48},
 {'_id': ObjectId('698d5b64d929263d0f2a0a93'),
  'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'AMD A6-Series 9220 2.5GHz',
  'Ram': '4GB',
  'Memory': '256GB SSD',
  'Gpu': 'AMD Radeon R4 Graphics',
  'OpSys': 'Windows 10',
  'Weight': '1.86kg',
  'Price': 21231.5472},
 {'_id': ObjectId('698d5b64d929263d0f2a0a94'),
  'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 13.3,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i7 8550U 1.8GHz',
  'Ram': '8GB',
  'Memory': '512GB SSD',
  'Gpu': 'Intel UHD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '1.49kg',
  'Price': 58767.84},
 {'_id': ObjectId('698d5b64d929263d0f2a0a95'),
  'Company': 'Acer',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Core i3 7100U 2.4GHz',
  'Ram': '4GB',
  'Memory': '1TB HDD',
  'Gpu': 'Intel HD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '2.4kg',
  'Price': 20459.52},
 {'_id': ObjectId('698d5b64d929263d0f2a0a96'),
  'Company': 'Dell',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i7 8550U 1.8GHz',
  'Ram': '8GB',
  'Memory': '256GB SSD',
  'Gpu': 'AMD Radeon 520',
  'OpSys': 'Windows 10',
  'Weight': '2.13kg',
  'Price': 40908.384},
 {'_id': ObjectId('698d5b64d929263d0f2a0a97'),
  'Company': 'HP',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i3 6006U 2GHz',
  'Ram': '4GB',
  'Memory': '128GB SSD',
  'Gpu': 'Intel HD Graphics 520',
  'OpSys': 'Windows 10',
  'Weight': '1.91kg',
  'Price': 23389.92},
 {'_id': ObjectId('698d5b64d929263d0f2a0a98'),
  'Company': 'Asus',
  'TypeName': 'Notebook',
  'Inches': 15.6,
  'ScreenResolution': '1366x768',
  'Cpu': 'Intel Core i5 7200U 2.5GHz',
  'Ram': '4GB',
  'Memory': '256GB SSD',
  'Gpu': 'Intel HD Graphics 620',
  'OpSys': 'Windows 10',
  'Weight': '2kg',
  'Price': 31232.2032},
 {'_id': ObjectId('698d5b64d929263d0f2a0a99'),
  'Company': 'MSI',
  'TypeName': 'Gaming',
  'Inches': 17.3,
  'ScreenResolution': 'Full HD 1920x1080',
  'Cpu': 'Intel Core i7 7700HQ 2.8GHz',
  'Ram': '16GB',
  'Memory': '256GB SSD +  2TB HDD',
  'Gpu': 'Nvidia GeForce GTX 1070',

In [76]:
df2 = pd.DataFrame(list(cursor))

In [77]:
df2.head()

,_id,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,698d5b64d929263d0f2a0a5f,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,698d5b64d929263d0f2a0a60,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,698d5b64d929263d0f2a0a61,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,698d5b64d929263d0f2a0a62,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,698d5b64d929263d0f2a0a63,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080